### ISSUE TITLE
cmd/cue: cmd exec.Run runner of kind "XXX" not found with k8s resources

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1061]
_Originally opened by @b4nst in https://github.com/cuelang/cue/issues/1061_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

I'm still trying to cut down my module in order to send something short that reproduces my issue.

```cue
command: deploy: {
	apply: exec.Run & {
		r:                  release.#Release
		stdin: r.output
		cmd:   "cat"
	}
}
```
`r.output` being a string generated by a `yaml.MarshalStream` of a list in `release.#Release`. This list contains Kubernetes definitions.

I've noticed that if I use `yaml.Marshal(single-resource)` it works. It does not work with a list comprehension + `strings.Join` (same error)
The command works if I replace `exec.Run` by `cli.Print` with proper changes (`stdin` --> `text`, remove `cmd`)

### What did you expect to see?

Command executed with sucess (prints `r.output` content)

### What did you see instead?

Prints `r.output` content then exit with error 

```
runner of kind "XXX" not found
```

XXX being the `kind` value of the first resource displayed (e.g. `Deployment`)

**Comment by myitcv** [comment]
Apologies for the delay in getting back to you, @b4nst we were busy with the migration (#1078)!

We're going to need a bit more to go on here. Have you had any luck reproducing this? 

If you have a large repro that's fine. If it's private, happy to reduce and discuss offline.

**Comment by b4nst** [comment]
I can't remember exactly what was the issue, but it seems I fixed it. I remember that for some reason, adding a nested level in the command for task seemed to work better (`command: deploy: task: apply` instead of `command: deploy: apply`). 

I think we can close this one since I ended up achieving my goals by cleaning my code. I strongly suspect PEBAK on this one. I can reopen it if I achieve to reproduce it. Thanks for your answer, and don't worry for the delay!

**Comment by myitcv** [comment]
Thanks for the quick follow up, @b4nst!

**Comment by astraios** [comment]
Hey, I'm afraid I'm facing the same issue in a very similar context.

I'm attaching a small public repo with a reproducible example: https://github.com/astraios/cuelangfoo

Each time you run `cue build`, it will fail because of:

```shell
cue build
runner of kind "ServiceAccount" not found
```

**Comment by eonpatapon** [comment]
@astraios In your example you are passing a k8s resource, not an actual cue task

The thing is `cue` determines something is a task by looking a some particular attribute `$id`, but also for historic reasons `kind`. Since your k8s resource has a `kind` field it thinks it is a task and tries to run go code associated with it. Obviously this code doesn't exists.

https://github.com/cuelang/cue/blob/master/cmd/cue/cmd/custom.go#L168

**Comment by astraios** [comment]
OIC, thanks for that insight. I had a look at that file yesterday, but the fact that I was trying to turn my "Release" structure into an actual cue "task" completely escaped me. With the following approach it works!!!

```
command: build: {
	// Write manifests
	task: writeManifest: file.Create & {
		filename: "manifests.yaml"
		contents: yaml.Marshal(foo.Release.manifests.default.ServiceAccount."test-sa")
	}
}
```

My original idea was to have a "variable" I could work with in tasks. I guess my approach is not a correct one...
Thanks for the help!!!
