### ISSUE TITLE
internal/eval: bare unary expression results in a Noop operator

### ISSUE THREAD

**Issue by srikrsna** [cue-lang/cue#1119]
### Discussed in https://github.com/cue-lang/cue/discussions/1094

<div type='discussions-op-text'>

<sup>Originally posted by **srikrsna** July 13, 2021</sup>
Hey everyone, I am trying to use Cue for validation. I wanted to built a protoc plugin that would generate validation functions based on `cue.value`  field option to various languages. Starting with Go and Dart. I am trying to parse a simple expressions but the below code always returns NoOp.
```go
package main
import (
	"cuelang.org/go/cue/cuecontext"
	"github.com/davecgh/go-spew/spew"
)
func main() {
	ctx := cuecontext.New()
	const expr = `>30`
	op, vv := ctx.CompileString(expr).Expr()
	// op is always NoOp
	spew.Dump(op, vv)
}
```
Can anyone guide me in the right direction?</div>

**Comment by myitcv** [comment]
Thanks for raising an issue for this, @srikrsna. The issue is perhaps best demonstrated by the following repro:

```
go mod tidy
go run main.go
cmp stdout stdout.golden

-- go.mod --
module mod.com

go 1.16

require cuelang.org/go v0.4.0
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue/cuecontext"
)

func main() {
	ctx := cuecontext.New()

	const expr1 = `>30`
	v1 := ctx.CompileString(expr1)
	op1, vv1 := v1.Expr()
	fmt.Printf("expr1: op %#v (%T), %#v\n", op1, op1, vv1)

	const expr2 = `x: >30`
	v2 := ctx.CompileString(expr2).Lookup("x")
	op2, vv2 := v2.Expr()
	fmt.Printf("expr2: op %#v (%T), %#v\n", op2, op2, vv2)
}
-- stdout.golden --
expr1: op 14 (adt.Op), []cue.Value{30}
expr2: op 14 (adt.Op), []cue.Value{30}
```

which fails with:

```
> cmp stdout stdout.golden
[diff -stdout +stdout.golden]
-expr1: op 0 (adt.Op), []cue.Value{>30}
+expr1: op 14 (adt.Op), []cue.Value{30}
 expr2: op 14 (adt.Op), []cue.Value{30}
```

It seems the bare `>30` is not parsed as a unary operator, despite this seemingly being valid CUE.

**Comment by mpvl** [comment]
Analysis: in the failing form, the bound is implicitly wrapped in a struct. `Expr` doesn't handle structs. But of course now we have embedded scalars, it should. And in fact it does. The issue is that it only does one layer of unwrapping. So if you were to further unwrap the returned result, it would, in fact, unwrap as expected.

I would argue that this is undesirable at the least, though, as algorithms expect to be able to terminate on a Noop. The solution would be to detect if there is a single value and then further unwrap that.
