### ISSUE TITLE
playground: make modes consistent with cmd/cue commands

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1150]
The [CUE playground](https://cuelang.org/play) was created some time ago, and in that intervening time there have been a number of changes to `cmd/cue`. In particular, we have a much clearer idea of what the various `cmd/cue` commands should do (related is https://github.com/cue-lang/cue/issues/337). 

We should bring the playground in line with `cmd/cue`, not least to help reduce any difference/confusion between users' experience of `cmd/cue` commands and the modes of the same name in the playground.

**Comment by mvdan** [comment]
I believe that https://github.com/cue-lang/cue/issues/2417 did this; the "export" mode now requires the output to be final and concrete like `cue export` (https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1170814), and we added an "eval" mode that mimics `cue eval` (https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1170942).

This is not perfect, because cmd/cue's code is rather complex and does more than simply calling the Go API, but I think we're pretty much there in terms of exposing the same three main modes that cmd/cue has in terms of evaluating CUE files. Marking as fixed, but let me know if I got that wrong.
