### ISSUE TITLE
ci: release darwin arm64 build

### ISSUE THREAD

**Issue by spencergilbert** [cue-lang/cue#1179]
**Is your feature request related to a problem? Please describe.**
Only an amd64 release is included for darwin

**Describe the solution you'd like**
It would be great to have a native arm64 release included, though I haven't had any issues running the current darwin build with Rosetta

**Additional context**
Related: asdf-community/asdf-cue#20
It does appear that goreleaser supports this target as of v0.157.0, Go 1.16

**Comment by myitcv** [comment]
Hi @spencergilbert welcome to the CUE project!

Thanks for raising this. @caarlos0 kindly contributed https://github.com/cue-lang/cue/commit/370fac9b49332b5c22cba6731e539925e0215e29 recently which should address this in the next release. 

On the basis I'll close this issue, but please shout if there's anything I've missed in that conclusion.

**Comment by spencergilbert** [comment]
Dang, I searched issues and didn't see anything, I swear GitHub search never works for me.

Thanks!

**Comment by myitcv** [comment]
> GitHub search never works for me.

It's funny you say that, because I also struggle. Instead I tend towards using a Google search with `site:github.com/cue-lang/cue` as part of the search condition. But for some reason that I am following up with GitHub, that is not working for CUE's new home. So I'm limited to GitHub search too these days!
