### ISSUE TITLE
cue get go: blank identifiers (placeholders) not filtered out from a set of successive typed constants

### ISSUE THREAD

**Issue by knieriem** [cue-lang/cue#1183]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version v0.4.0 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

I'm trying to extract definitions from Go code that contains typed (and untyped) consts.

```
cue get go
-- a.go --
package a

type C int

// define some typed constants
const (
	A C = iota
	b
	_
	c
)

// define some untyped constants
const (
	D = iota
	e
	_
	f
)
-- go.mod --
module example.com/a

go 1.16
```

### What did you expect to see?

I expected to see generated CUE definitions, where the _blank identifier_ (`_`) is filtered out.

### What did you see instead?

This works for the untyped constants, but in case of the typed constants the `_` gets transformed into a cue reference `_#_` that cannot be resolved:

```cue
#enumC:
	#A |
	_#b |
	_#_ |       // <-----
	_#c

#values_C: {
	A: #A
	b: _#b, "_": _#_         // <-----
	c: _#c
}
```

It seems that this behaviour is fixed by the following change:

```go
--- a/cmd/cue/cmd/get_go.go
+++ b/cmd/cue/cmd/get_go.go
@@ -716,6 +716,9 @@ func (e *extractor) reportDecl(x *ast.GenDecl) (a []cueast.Decl) {
 				var exprs []cueast.Expr
 				var named []cueast.Decl
 				for _, v := range enums {
+					if v == "_" {
+						continue
+					}
 					label := cueast.NewString(v)
 					cueast.SetRelPos(label, cuetoken.Blank)
```
 
This way `_` gets ignored the same way as compared to some lines below that position: https://github.com/cue-lang/cue/blob/0f53054da7243c7a312cd0ad54a1083d67c185d3/cmd/cue/cmd/get_go.go#L767-L770

**Comment by myitcv** [comment]
Hi @knieriem, welcome to the CUE project!

Thanks for raising this, and for the repro (I assume you follow the [guidance in the wiki](https://github.com/cue-lang/cue/wiki/Creating-test-or-performance-reproducers)). I agree this needs to be fixed.

Here is a complete repro that also shows the expected result:

```
go mod tidy

# Run get go
exec cue get go --local .
cmp a_go_gen.cue a_go_gen.cue.golden

-- a.go --
package a

type C int

// define some typed constants
const (
	A C = iota
	b
	_
	c
)

// define some untyped constants
const (
	D = iota
	e
	_
	f
)
-- go.mod --
module example.com/a

go 1.16
-- a_go_gen.cue.golden --
// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go example.com/a

package a

#C: int // #enumC

#enumC:
	#A |
	_#b |
	_#c

#values_C: {
	A: #A
	b: _#b
	c: _#c
}

#A:  #C & 0
_#b: #C & 1
_#c: #C & 3

#D:  0
_#e: 1
_#f: 3
```

If you would like to send a PR, please do! Otherwise, if you would like to contribute via Gerrit, please see the [contribution guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md) (noting that in #1198 we need to expand that contribution guide to more clearly mention the PR process)
