### ISSUE TITLE
Loop repeats last valid value or nothing

### ISSUE THREAD

**Issue by fionera** [cue-lang/cue#1272]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Example 1:
```
input: {
	"key 0": 1
	"key 1": "test"
	"key 2": {
		"bar": "foo"
	}
}

output: {
	for k, v in input {
		_val: string | *v

		"\(k)": _val
	}
}
```

Example 2:
```
input: {
	"key 0": 1
	"key 1": "test"
	"key 2": "test2"
	"key 3": {
		"bar": "foo"
	}
}

output: {
	for k, v in input {
		_val: string | *v

		"\(k)": _val
	}
}
```

### What did you expect to see?
There should be an error because there is a conflicting value.

### What did you see instead?
Example 1:
```
{
    "input": {
        "key 0": 1,
        "key 1": "test",
        "key 2": {
            "bar": "foo"
        }
    },
    "output": {
        "key 0": "test",
        "key 1": "test",
        "key 2": "test"
    }
}
```

Example 2:
```
output:
```

**Comment by verdverm** [comment]
If you unroll these loops, you get the following. (I'm using `val` instead of `_val` so I can see the result.

https://cuelang.org/play/?id=J1WYDGXbSuv#cue@export@cue

example 1:

`val: (string | *1) & (string | *"test") & (string | *{ bar: "foo"})` => `val: "test"

example 2:

`val: (string | *1) & (string | *"test") & (string | *"test2") & (string | *{ bar: "foo"})` => `val: string | "test2" | "test"`

---

I suspect this is working as intended. The for "loop" is really a comprehension and the `_val` is being added to for each element. You can get an error for incomplete disjunction on the second example depending on what command your run. In the play above, switch the output to JSON.

The rules around how defaults work can be found in the spec here: https://cuelang.org/docs/references/spec/#default-values

**Comment by mpvl** [comment]
@verdverm is correct.
