### ISSUE TITLE
cue: Value.Eval() does not enforce concreteness

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1326]
### What version of CUE are you using (`cue version`)?

v0.4.0

### What did you do?

```go
go run main.go

-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/errors"
)

const val = `
v: {
	i: int
	s: "hello"
}
`

func main() {
	c := cuecontext.New()
	v := c.CompileString(val, cue.Filename("val.cue"))

	// check for errors during compiling
	if v.Err() != nil {
		msg := errors.Details(v.Err(), nil)
		fmt.Printf("Compile Error:\n%s\n", msg)
	}

	// eval evaluates and returns a new value
	e := v.Eval()
	if e.Err() != nil {
		msg := errors.Details(e.Err(), nil)
		fmt.Printf("Eval Error:\n%s\n", msg)
	}

	fmt.Printf("%#v\n", e)
}
```

### What did you see?

```cue
v: {
        i: int
        s: "hello"
}
```

### What did you expect to see?

An error about `i` being incomplete. The docs talk about not needing to use `Eval` to get a concrete value, which leads one to believe that it enforces concrete values. I believe this used to be the behavior?

- `Eval`: https://github.com/cue-lang/cue/blob/v0.4.0/cue/types.go#L714
- `ToDataSingle`: https://github.com/cue-lang/cue/blob/master/internal/core/adt/composite.go#L349

**Comment by antong** [comment]
I ran the example, and got exactly what is under "What did you expect to see?". 😕

**Comment by verdverm** [comment]
The section headers were backwards (now fixed), I naturally think `code > output =? expected`

**Comment by myitcv** [comment]
I think this is working as intended, because `Eval()` does not claim to recursively resolve references, which I believe is what you're looking to do above. Consider:

```
go mod tidy
go run main.go
stdout 5

-- go.mod --
module mod.com

go 1.16

require cuelang.org/go v0.4.0
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

const val = `
i: x
x: 5
`

func main() {
	c := cuecontext.New()
	v := c.CompileString(val, cue.Filename("val.cue"))

	i := v.LookupPath(cue.MakePath(cue.Str("i")))
	i = i.Eval()
	fmt.Printf("%#v\n", i)
}
```

which passes, i.e. the output is:

```
> go mod tidy
> go run main.go
[stdout]
5
```

@verdverm thanks for your txtar repros. Unfortunately your repro doesn't work with a straight copy-paste piped to [`testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal@v1.8.0/cmd/testscript) because of the missing `go.mod` file and corresponding `go mod tidy` to populate the `go.sum` file. FWIW I tend to elide `go.sum` files in repros for brevity and use `go 1.16` for succinctness of `go.mod`.

**Comment by antong** [comment]
I also don't understand what the sentence "This method is not necessary to obtain concrete values." in the documentation really means. I didn't interpret it as I guess @verdverm  did (sorry if I read you wrong), like that if the docs say Eval is not necessary to get concrete values, then that would imply that Eval is sufficient to get concrete values. I just accepted that I don't understand what Eval is for :-)

> The docs talk about not needing to use Eval to get a concrete value, which leads one to believe that it enforces concrete values.

**Comment by myitcv** [comment]
We could certainly look to repurpose this issue to clarify the docs for `Value.Eval()`. My understanding is that the phrase (as confusing as it might be) is intended to indicate that other methods should be used when looking to (recursively) make concrete a `cue.Value`, and that a prior call to `Value.Eval()` is not required. For example, if a `cue.Value` `v` represents a struct value, I would use `cue.Value.Decode()` in order to make that concrete. Errors would be reported if that operation failed. Similarly for `cue.Value.String()` etc.

**Comment by verdverm** [comment]
`Value.Decode(interface{})` would put the concrete data into a Go native type.

What if I want a concrete `cue.Value` from a value I already have? There doesn't seem to be a function for that currently.

(pseudo code, overlapping with the `Evaluate(...Options)` issue (#1327)
```
for i := range [1,2,3] {
  f := val.FillPath("input", i)
  c := f.Evaluate(cue.Concrete(true))
  o := c.LookupPath("output")
  ...
}
```

Here `val` is some transform (the T in ETL), that I may want to reuse.

**Comment by myitcv** [comment]
> What if I want a concrete `cue.Value` from a value I already have

I'm not clear what the use case driving this is though. I understand what you are saying, but what use case is driving this? What do you then do with the resulting value(s)?

**Comment by verdverm** [comment]
Is there a difference between `Evaluate(cue.Concrete(true))` and `Evaluate(cue.Concrete(true),cue.Final())`? Would I be able to add more fields to the first and not the second?

One thing I might want to do is `Walk` the value after it has been made concrete. How would one do that today?
