### ISSUE TITLE
fmt and eval output have different formatting for structs in lists

### ISSUE THREAD

**Issue by mxey** [cue-lang/cue#1391]
I think `cue fmt` should format CUE code in the same format that `cue eval` prints it (or `cue import` generates it). 

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

v0.4.0 is the latest release.

### What did you do?

Run this testscript:

```
exec cue fmt x.cue
exec cue eval x.cue
cmp stdout x.cue

-- x.cue --
[
    {key: "value"},
    {key: "value"},
]
```

### What did you expect to see?

```
PASS
```

### What did you see instead?

```
> exec cue fmt x.cue
> exec cue eval x.cue
[stdout]
[{
    key: "value"
}, {
    key: "value"
}]
> cmp stdout x.cue
--- stdout
+++ x.cue
@@ -1,5 +0,0 @@
-[{
-    key: "value"
-}, {
-    key: "value"
-}]
@@ -0,0 +1,4 @@
+[
+       {key: "value"},
+       {key: "value"},
+]

FAIL: /var/folders/yk/v64pl_sj1v98rtz0tz2y3zch0000gp/T/testscript202127078/example.testscript/script.txt:3: stdout and x.cue differ
error running example.testscript in /var/folders/yk/v64pl_sj1v98rtz0tz2y3zch0000gp/T/testscript202127078/example.testscript
```

**Comment by rogpeppe** [comment]
@mxey Thanks for the report.

I'm not sure this issue is going to be possible to fix in general.
By necessity, `cue fmt` does not convert to a truly canonical form - it leaves some leeway for user-chosen
formatting. For example, it will preserve the vertical white space between fields below:

```
a: 1

b: 2
```

On the other hand, `cue eval` is printing an expression that's the result of arbitrary unification: it _is_ producing some kind of canonical form because it has to.

These two properties would seem to be in opposition to one another.

That said, I do believe that `cue fmt` could be somewhat more opinionated. I've seen examples of manifestly badly formatted CUE that `cue fmt` leaves intact. For example, `cue fmt` could have reformatted the input above to:

```
[{
	key: "value"
}, {
	key: "value"
}]
```

in which case there would be no diff in this particular case.
That seems to me like a somewhat different issue, and I think we should just open individual `fmt`-tagged issues for specific shortcomings of `cue fmt` itself (such as https://github.com/cue-lang/cue/issues/1432).

As such, I'll close this issue. @mxey please raise specific issues against `cue fmt` if you think that's appropriate.
