### ISSUE TITLE
value.Decode(x interface{}) not handling nested incomplete values  

### ISSUE THREAD

**Issue by addreas** [cue-lang/cue#1401]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
0.4.0
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
```go
go mod tidy
go run main.go
stdout '^map\[b:\[0\]\]$'

-- go.mod --
module mod.com

go 1.16

require cuelang.org/go v0.4.0
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

const val = `
a: b: _ | *[0, ...]
`

func main() {
	c := cuecontext.New()
	v := c.CompileString(val, cue.Filename("val.cue"))

	content := make(map[string]interface{})
	err := v.Decode(&content)

	if err != nil {
		fmt.Printf("%v\n", err)
	} else {
		fmt.Printf("%v\n", content["a"])
	}
}

```

### What did you expect to see?
That the decoding would recursively apply default values.

### What did you see instead?
`a.b: cannot convert non-concrete value [0]

Currently working around it with whats suggested [here](https://github.com/cue-lang/cue/issues/1327#issuecomment-954930097) before decoding. I guess this todo indicates that this is a know issue as well? 

https://github.com/cue-lang/cue/blob/b89ad85f14a454807931e24a86ee18df58432552/cue/decode.go#L103.

**Comment by eonpatapon** [comment]
`value.Decode()` is applying default values https://github.com/cue-lang/cue/blob/master/cue/decode.go#L83.

After a little debugging session it seems problem is while the default value `[0, ...]` is correctly picked up it is considered as an error because is it not closed (https://github.com/cue-lang/cue/blob/master/cue/types.go#L891). However `value.Default()` should close it (per it's comment).

The following patch fixes the issue:

```diff
diff --git a/internal/core/adt/default.go b/internal/core/adt/default.go
index ad88f0da..1fecff6d 100644
--- a/internal/core/adt/default.go
+++ b/internal/core/adt/default.go
@@ -74,7 +74,7 @@ func (v *Vertex) Default() *Vertex {
                        expr, _ := stripNonDefaults(c.Expr())
                        w.Conjuncts = append(w.Conjuncts, MakeRootConjunct(c.Env, expr))
                }
-               return w
+               return w.Default()

        case *ListMarker:
                m := *d
```

The default vertex is taken from the disjunction, it has kind list but the list is still open. By calling `Default()` again on the created vertex we hit the `*ListMarker` case below which will close the list.

Not too familiar with this part of the code base so I leave this here for @mpvl to have a look ;)

**Comment by mpvl** [comment]
@eonpatapon you are correct.

Change a-coming.
