### ISSUE TITLE
Better syntax support for user-defined "functions"

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1480]
https://github.com/cue-lang/cue/discussions/484#discussioncomment-959801

**Is your feature request related to a problem? Please describe.**

Per https://github.com/cue-lang/cue/discussions/484, user-defined "functions" are somewhat clumsy right now in that they have to be defined via something like:

```cue
#udf: {
  #foo: string
  out: "\(#foo)bar"
}

"quux": (#udf & {#foo: "foo"}).out
```

with named parameter fields and an output field

**Describe the solution you'd like**

Per @mpvl, something like this could work:

```cue
#udf: {
  #0: string
  
  "\(#0)bar"
}

"quux": #udf("foo")
```

which uses a combination of numbered definitions as parameter fields and an embedded scalar as the result.

Open question: how struct values would work in this case.

**Describe alternatives you've considered**

The workaround described above.

**Additional context**

n/a

**Comment by madhadron** [comment]
Would something closer to Prolog be more general and more useful? A first cut:

```
{
    n: 42,
    paddedN: s |- pad10 & { out: s, n: n }
}

pad10 { n: <10, out: "0\(n)" }
pad10 { n: >=10, out: "\(n)" }
```

where `|-` is a "given that" sign. The expression to the left of `|-` is evaluated after the expression on the right is unified. Then we can  write things like

```
s |- (s<100 & pad10 & { out: s, in: n }) | s="too big"
```

This kind of layering of guards and conditionals is something we would do in a sequence of expressions in an imperative language. In Cue right now, it has to be moved somewhere else in the program instead of being kept local to the value.

**Comment by myitcv** [comment]
Closing this in favour of https://github.com/cue-lang/cue/issues/943, specifically the first section "Functions"

**Comment by mvdan** [comment]
For those following this thread, please see our proposal and experimental support for CUE functions: https://github.com/cue-lang/cue/discussions/4484
