### ISSUE TITLE
internal/eval: cycle detection too strict?

### ISSUE THREAD

**Issue by bluescreen303** [cue-lang/cue#1492]
### What version of CUE are you using (`cue version`)?

cue version 0.4.1 linux/amd64

### Does this issue reproduce with the latest release?

I believe 0.4.1 is the latest release

### What did you do?

I tried to model lists with an even number of elements (pairs) which are sorted.
All is fine when putting the list into a struct that performs these validations, but when I want to take things "top level" by using an embedding, cycle detection kicks in.

```
import "list"

#SortedPairs: {
  _even_length: rem(len(items), 2) & 0
  _sorted: list.Sort(items, list.Ascending)
  _is_sorted: _sorted & items
  items: [...int]
}

test1: #SortedPairs & {
    items: [1,2,3,4,5,6]
}

#SortedPairsList: self={
  _even_length: rem(len(self), 2) & 0
  _sorted: list.Sort(self, list.Ascending)
  // _is_sorted: _sorted & self
  [...int]
}

test2: #SortedPairsList
test2: [1,2,3,4,5,6]
```

### What did you expect to see?

For the struct-version (SortedPairs), changing test1 to [1,2,3,4,5,4] triggers an error as expected.
For the top level list version (SortedPairsList), I would expect the same.

### What did you see instead?

I cannot enable the sorting check. Uncommenting that line triggers cycle detection.

**Comment by myitcv** [comment]
Strictly speaking I think this _is_ a structural cycle. cc @mpvl for confirmation. 

**Edit:** see https://github.com/cue-lang/cue/issues/1492#issuecomment-1024028175

~The way to handle this case is to use a [`let` declaration](https://cuelang.org/docs/references/spec/#let-declarations) instead of a value alias:~

```
exec cue eval -c x.cue
cmp stdout stdout.golden

-- x.cue --
import "list"

#SortedPairs: {
	_even_length: rem(len(items), 2) & 0
	_sorted:      list.Sort(items, list.Ascending)
	_is_sorted:   _sorted & items
	items: [...int]
}

test1: #SortedPairs & {
	items: [1, 2, 3, 4, 5, 6]
}

#SortedPairsList: {
	_even_length: rem(len(self), 2) & 0
	_sorted:      list.Sort(self, list.Ascending)
	let self = [...int]
	self
}

test2: #SortedPairsList
test2: [1, 2, 3, 4, 5, 6]
-- stdout.golden --
test1: {
    items: [1, 2, 3, 4, 5, 6]
}
test2: [1, 2, 3, 4, 5, 6]
```

**Comment by bluescreen303** [comment]
I agree that it *is* a cycle, strictly speaking.
Your solution does not have the cycle issue, but now `[1,2,3,4,5,6,1]` is accepted as test2, violating both constraints.

I tried the let-version before I remember. This is probably another issue where self isn't unified with the output while the constraints evaluate, perhaps using some default such as `[]`. But I'm just guessing as I don't know the implementation.

**Comment by myitcv** [comment]
@bluescreen303 thanks for reverting. My suggestion to use `let` here is actually wrong, because the constraints simply validate that `[...int]` is sorted and of even length, which is trivially true. Was clearly too early when I replied!

This is actually a case where a value alias should be possible with the embedded scalar value:

```
import "list"

#SortedPairs: {
	_even_length: rem(len(items), 2) & 0
	_sorted:      list.Sort(items, list.Ascending)
	_is_sorted:   _sorted & items
	items: [...int]
}

test1: #SortedPairs & {
	items: [1, 2, 3, 4, 5, 6]
}

#SortedPairsList: {
	_even_length: rem(len(self), 2) & 0
	_sorted:      list.Sort(self, list.Ascending)
	self=[...int]
}

test2: #SortedPairsList
test2: [1, 2, 3, 4, 5, 6]
```

But I think there must be some vestiges of the migration from the old alias approach to the new one because this results in:

```
use of deprecated old-style alias; use "let X = expr" instead (deprecated as of v0.1.4): try running `cue fix` (possibly with an earlier version, like v0.2.2) to upgrade:
    ./x.cue:17:2
```

Again, leaving for @mpvl to comment here.

**Comment by bluescreen303** [comment]
I don't oversee the implementation details here on the let binding and the alias. Are you saying that a let-expression is merely an expression substitution so that each usage of `self` would translate into just putting `[...int]` in place, without referring to a single value that is being unified by all usage sites?

If so, I think that's highly confusing behaviour when compared to other languages.

**Comment by mpvl** [comment]
There is a structural cycle as the `_is_sorted` field is repeated recursively. The trick is to discard the unnecessary fields. This can be done, for instance, by using a comprehension as such:

```
import "list"

#SortedPairsList: self={
	_even_length: rem(len(self), 2) & 0
	_sorted: list.Sort(self, list.Ascending)
	_is_sorted: _sorted & [ for x in self {x} ]
	[...int]
}

test2: #SortedPairsList
test2: [1,2,3,4,5,6]
```


We should find an easier and more intuitive way to handle this though. I think a `list.Sorted` builtin makes sense.
But more generally, I could imagine a "concrete value" comparator, like `equalsConcrete(a, b)` or `a === b` that only compares concrete values, analogous to the Prolog difference `=` vs `==`. As a pre v1 consideration, we could also decide that `==` _is_ like the Prolog `==`, meaning comparing only concrete values. This is more or less how`==` works now anyway. With the proposed builtin `must` the solution would then become:

```
#SortedPairsList: self={
	must(rem(len(self), 2) == 0)
	_sorted: list.Sort(self, list.Ascending)
	must(_sorted == self)
	[...int]
}
```

**Comment by mpvl** [comment]
In fact, come to think of this, `==` already works like this for lists :):
```
import "list"

#SortedPairsList: self={
	_even_length: rem(len(self), 2) & 0
	_sorted: list.Sort(self, list.Ascending)
	_is_sorted: true & (_sorted == self)
	[...int]
}

test2: #SortedPairsList
test2: [1,2,3,4,6,5]
```

**Comment by bluescreen303** [comment]
Thanks. That fixes my issue. I like the list comprehension version better, although it's clunky. Having to revert to boolean logic in type systems and logic systems doesn't sound right.

But it does not explain why this version does not validate the constraints:
```
#SortedPairsList: {
	_even_length: rem(len(self), 2) & 0
	_sorted:      list.Sort(self, list.Ascending)
	let self = [...int]
	self
}
```
Because `self` is unified with the output being returned, so it doesn't make sense to me that it is evaluated as `[]` in `_sorted` and `_even_length`.

And it also doesn't explain why this version throws a deprecation error:
```
#SortedPairsList: {
	_even_length: rem(len(self), 2) & 0
	_sorted:      list.Sort(self, list.Ascending)
	self=[...int]
}
```

Should I create separate issues for these?

**Comment by mpvl** [comment]
> But it does not explain why this version does not validate the constraints:

`let self = [...int]` just set's a value to `[...int]`.  Embedding `self` just references that value which then unifies it with the outer struct. But like all references in CUE, the binding only happens in one direction. So the value of `self` itself is not modified by embedding it in `#SortedPairsList`. In other words, `list.Sort(self, list.Ascending)` results in the empty list, as `self` is just bound to `[...int]`, which simplifies to the empty list.

Note that this is indeed different from some other logic programming languages, like Prolog, where an identifier bound to a value can be two directional (they are more like `holes` to be filled). There is something to say for doing something like that in CUE too. But based on use case analysis, we observed that there is a strong need for one-directional resolution in configuration. And we preferred to have only one mechanism. 

> And it also doesn't explain why this version throws a deprecation error:

The notation `self=[...int]` is not allowed. This used to mean the same as `let self = [...int]` (before let was introduced), but that notation was too confusing, as the `x=y` notation is otherwise used to create aliases. In the future, we  may consider allowing `a: { x=y }` to mean the same as `a: x={y}`. 

Note that `let` is distinctly not an alias. It is just an identifier bound to an expression. One could view it as a field that is only visible within the syntactic scope and nowhere else. Its purpose is to avoid repeating sub expressions, or to break complex expressions up in manageable pieces. Syntactically it is a generalization of comprehensions.

**Comment by bluescreen303** [comment]
thank you. That clarifies it.

The uni-directional logic probably takes some getting used to. Especially since everything seems centered around unification, which for me (Haskell type system background) has a bidirectional association as well.
