### ISSUE TITLE
cue/cmd: new http tls support breaks when not specified

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#1594]
I think the TLS support commit https://github.com/cue-lang/cue/commit/da75cdf385d3eebfb2db363a9ad9447c70be58b1 breaks code like this:

```
exec cue cmd main
-- in.cue --
command: main: {
  call: { $id: "tool/http.Do", method: "GET", url: "https://postman-echo.com/get", response: body: string }
  print: { $id: "tool/cli.Print", text: call.response.body }
}
```

I would expect that generally, since it defaults to true, I ought not to have to specify it. Thinking there needs to be a check to see if the `tls.verify` field exists before trying to access it like a bool here: https://github.com/cue-lang/cue/blob/master/pkg/tool/http/http.go#L52

### What did you expect to see?

```
$ cue cmd main ./in.cue 
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-623be105-1f6e73444f2cd3366aad6694","accept-encoding":"gzip","user-agent":"Go-http-client/2.0"},"url":"https://postman-echo.com/get"}
```

### What did you see instead?

```
command.main.call: invalid bool argument: field not found: tls:
    ./in.cue:2:3
```

**Comment by verdverm** [comment]
`0001-fix-tls-error.patch`:

```
From 0ac9a574009f8f8e46e77467561d7ca34efb554b Mon Sep 17 00:00:00 2001
From: Tony Worm <tony@hofstadter.io>
Date: Wed, 23 Mar 2022 23:29:26 -0400
Subject: [PATCH 1/1] fix tls error

Signed-off-by: Tony Worm <tony@hofstadter.io>
---
 pkg/tool/http/http.go | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

diff --git a/pkg/tool/http/http.go b/pkg/tool/http/http.go
index 61bff513..7670bd21 100644
--- a/pkg/tool/http/http.go
+++ b/pkg/tool/http/http.go
@@ -49,7 +49,7 @@ func (c *httpCmd) Run(ctx *task.Context) (res interface{}, err error) {
        var (
                method    = ctx.String("method")
                u         = ctx.String("url")
-               tlsVerify = ctx.BoolPath(cue.ParsePath("tls.verify"))
+               tlsVerify = true
        )
        var r io.Reader
        if obj := ctx.Obj.Lookup("request"); obj.Exists() {
@@ -77,6 +77,13 @@ func (c *httpCmd) Run(ctx *task.Context) (res interface{}, err error) {
                        return nil, errors.Wrapf(err, caCertValue.Pos(), "invalid bytes value")
                }
        }
+       verifyValue := ctx.Obj.LookupPath(cue.ParsePath("tls.verify"))
+       if verifyValue.Exists() {
+               tlsVerify, err = verifyValue.Bool()
+               if err != nil {
+                       return nil, errors.Wrapf(err, verifyValue.Pos(), "invalid bool value")
+               }
+       }
 
        if ctx.Err != nil {
                return nil, ctx.Err
@@ -85,6 +92,7 @@ func (c *httpCmd) Run(ctx *task.Context) (res interface{}, err error) {
        transport := http.DefaultTransport.(*http.Transport).Clone()
        transport.TLSClientConfig = &tls.Config{}
 
+
        if !tlsVerify {
                transport.TLSClientConfig.InsecureSkipVerify = true
        }
-- 
2.20.1
```

**Comment by eonpatapon** [comment]
In your example you don't import the `tool/http.Do` schema but instead specify the `$id` of the runner to use.

IMO by doing this you put yourself at risk as you don't track the runner schema.

This raises questions about which guarantees the runners code needs to provide.

Should the code assume the tool schema is used and therefore doesn't need to check if every default field exists ? Or should we basically duplicate the handling of all default values in the code like you did in your patch for `tls.verify` ?

I believe the standard way of doing things would be to import and use the tool schema and let cue resolve the defaults properly.

I guess you did this to be able to share commands in a package ? And to do this you can't import tool packages ? If it's the case I think you hit this because you workaround other limitations.

**Comment by verdverm** [comment]
- Yes, this issue came up via having imported packages of tasks.
- This is valid code, there should be no requirement to unify with the schema
- The change introduced a backwards incompatible break
- IMO, the `cue cmd` code base should be more defensive. Checking the existence of fields before casting them is done for the other field (caCert), so why not the `verify` fields?
- One thing I've been doing in `hof/flow` is to embed and unify with the schema in the code. In that way I do not need to mirror the defaults in the code.

I think for a patch release, we should not be introducing breaking changes.

**Comment by eonpatapon** [comment]
I understand the frustration when something breaks but it is a beta release so there is still time to make things right.

If the code needs to be more defensive I don't mind doing it. 

In the case of `caCert` it is an optional field so it is necessary to check if it exists. For `verify` it is required and has a default in the schema so I've assumed the user unifies the task with it's schema. I think that's the standard and documented way of using tasks.

A similar example is the `permission` field in `file.Create`. There is a default in the schema and the code assumes it exists and will fail if not set.

I think `cue cmd` could unify tasks schemas itself but that would mean 2 unifications for each task if the user has imported and unified the tasks schemas in it's configuration.

Also I believe if you were allowed to import `tool/*` in your package you probably would have do it like that instead of manually specifying `$id`. In that case this discussion would have never happen :)

**Comment by myitcv** [comment]
> This is valid code, there should be no requirement to unify with the schema

Just to flag, we have previously discussed moving away from the approach of defining tasks is via `$id` fields. 

Nothing concrete yet, but any change would happen as part of https://github.com/cue-lang/cue/issues/1325
