### ISSUE TITLE
pkg/net: Add QueryEscape, QueryUnescape, PathEscape, PathUnescape

### ISSUE THREAD

**Issue by eraserhd** [cue-lang/cue#1699]
**Is your feature request related to a problem? Please describe.**

I needed to take secrets from a secret store and build a URL which contains a password.  This required escaping the password for insertion into the URL.  It was [possible to do so](https://gist.github.com/eraserhd/1a227dbac1ce1202463dffab95061489)possible to do so without, but it was no walk in the park, even though this seems like a common enough use case.

(Note that the above-mentioned code could also use a way to convert a byte array or a rune array into a string, which also does not appear to exist.)

**Describe the solution you'd like**

Implementation of `net.QueryEscape`.

The other three functions are for completeness.

**Describe alternatives you've considered**

[Hand-written CUE](https://gist.github.com/eraserhd/1a227dbac1ce1202463dffab95061489)

Hand-written CUE, but adding just a rune-to-string function.
 
Adding the user functions in a way that allows bi-directional unification -- not supported in today's CUE, but it would be nice.

This would require the user functions to be written more like prolog predicates, and the function can take two input/output args.  The code could check to see which arguments are ground and unify in the required direction, and update one or the other arg and return an error or nil.  This would allows something like:

```cue
{x: string, y: net.QueryEscape(x)} & {y: "f%25o"} //=> {x: "f%o", y: "f%25o"}
```

Clearly not generally implementable, but it could be done here.

I did not read the contributing document first, so I already made #1695 .

**Comment by myitcv** [comment]
> I did not read the contributing document first, so I already made #1695 .

No problem. Thanks for raising the issue for discussion, @eraserhd. That way we have an easy to search record of decisions and discussion.

> Adding the user functions in a way that allows bi-directional unification -- not supported in today's CUE, but it would be nice.

Such an approach was previously discussed; unfortunately I cannot find the issue/discussion/link. But as you say, this is outside the scope of CUE's evaluator as it stands today. For example, the following does not "solve": https://cuelang.org/play/?id=3-RTQltoECS#cue@export@cue

Regarding the proposal itself, just to confirm the implementation would effectively be a proxy to Go's `net/url.QueryEscape` etc? If so, that seems fine to me, because those functions are hermetic. 

But I defer to @mpvl for a final decision.

**Comment by mpvl** [comment]
These seem like desirable extensions indeed. I suspect the respective escaping logic is fixed by now, so this is okay to add.
