### ISSUE TITLE
evaluator: nested indirect selector(s) causes structural cycle

### ISSUE THREAD

**Issue by odipar** [cue-lang/cue#1708]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version v0.4.3 (CUE playground)

</pre>

### Does this issue reproduce with the latest release?

Not sure

### What did you do?
<pre>#add10: {
    in: number
    a10: { i: in, o: i + 10 }
    out: a10.o
}
k00: 0
k10: (#add10 & {in: k00}).out
k20: (#add10 & {in: k10}).out
k30: (#add10 & {in: k20}).out</pre>

### What did you expect to see?
<pre>k00: 0
k10: 10
k20: 20
k30: 30</pre>

### What did you see instead?
<pre>structural cycle:
    -:7:7</pre>

### Less nesting works! (removing k30)
<pre>#add10: {
    in: number
    a10: { i: in, o: i + 10 }
    out: a10.o
}
k00: 0
k10: (#add10 & {in: k00}).out
k20: (#add10 & {in: k10}).out</pre>

### ..with the expected result
<pre>k00: 0
k10: 10
k20: 20</pre>

### Possible explanation?
May be limited evaluation recursion depth causes cyclic structure errors, while there are no cycles?

**Comment by benmoss** [comment]
Validated as still present in 1ed6195cd8d0051bb2a59c68be8d6a9234ea7138

An even simpler version:
```
#add10: {
	in:  number
	out: in
}
k00: 0
k10: (#add10 & {in: k00}).out
k20: (#add10 & {in: k10}).out
k30: (#add10 & {in: k20}).out
```

**Comment by myitcv** [comment]
Even appears to be an issue with https://review.gerrithub.io/c/cue-lang/cue/+/537831/1.

Assigning to @mpvl.

**Comment by mpvl** [comment]
Intriguing. The evaluation order of this makes it that `#add10` is used in a reentrant fashion, causing it to be detected as a cycle. That is overruled, usually, by unifying it with non-cyclic conjuncts. In this case, the references in the `in` fields server that purpose, but as this is done "inline" instead of the usual mechanism, CUE probably misses these as it is a slightly different case from the usual one. IOW, to CUE this looks like evaluating
```
k30: (#add10 & {in: k30}).out
```
which would be a cycle.
