### ISSUE TITLE
cmd/cue: ignore flag on eval subcommand is not working

### ISSUE THREAD

**Issue by rabingaire** [cue-lang/cue#1786]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I tried running the example program from this -> [link of cue documentation](https://cuelang.org/docs/tutorials/tour/types/numbers/) and I get error even when `--ignore` flag is applied.

### What did you expect to see?
I expected it to behave like it does on that mentioned documentation link.

### What did you see instead?
Got an error message: `conflicting values int and 4.0 (mismatched types int and float)`

**Comment by rogpeppe** [comment]
Thanks for the report.

AIUI, the `--ignore` flag specifies that the errors are ignored for the purposes of continuing to process more instance arguments, but not that the errors are suppressed.

That said, I can't actually get the `--ignore` flag to work as advertised either, so there may well be a real issue here.

Here's an example I used to try to demonstrate the issue:

```
! exec cue export --ignore a.cue b.cue
stdout expect.json
-- a.cue --
a: string
-- b.cue --
b: "concrete"
-- expect.json --
{
	"b": "concrete"
}
```

I get this output:

```
> ! exec cue export --ignore a.cue b.cue
[stderr]
a: incomplete value string:
    ./a.cue:1:4
[exit status 1]
> stdout expect.json
FAIL: /tmp/testscript3233298218/x.txtar/script.txt:2: no match for `expect.json` found in stdout
```

At the very least, the `--ignore` flag should document what it means to "proceed in the presence of errors".

**Comment by myitcv** [comment]
I suspect that part of the solution here will involve defining exactly what kinds of errors can be ignored. That will likely become easier as part of #822.

**Comment by myitcv** [comment]
Noting that this broke as far back as 7f52c107b61980629c4c0d6751386a8ce360ddb9, but was masked by a bad fix in https://cue-review.googlesource.com/c/cue/+/6081.

**Comment by myitcv** [comment]
This should not have been closed. Naughty GitHub.

**Comment by mvdan** [comment]
> This should not have been closed. Naughty GitHub.

Oh, that was my bad! I never knew that writing "when we fix #NNN" as part of a sentence could still trigger the automation.

**Comment by myitcv** [comment]
It definitely seems like a GitHub bug as opposed to being your fault :)
