### ISSUE TITLE
cmd/cue: Input by user from prompt not parsed correctly

### ISSUE THREAD

**Issue by rabingaire** [cue-lang/cue#1793]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I was playing with cue scripting feature and wrote this little script
```
package foo

import (
    "tool/exec"
    "tool/cli"
)

city: "Kathmandu"

command: hello: {
    ask: cli.Ask & {
        prompt: "Your Name?"
        response: string
    }
    print: exec.Run & {
        cmd: "echo Hello \(ask.response)! Welcome to \(city)."
    }
}
```
I ran the following script using this command `cue cmd hello`
Now cue prompts me to give input
I give input with space character in it.

### What did you expect to see?
I expect cue to print `Hello Rabin Gaire! Welcome to Kathmandu.`

### What did you see instead?
`Hello Rabin! Welcome to Kathmandu.` and shell treats `Gaire` as a new command
```
rabingaire@dev:~/Desktop/cue 
$ cue cmd hello
Your Name? Rabin Gaire
Hello Rabin! Welcome to Kathmandu.
rabingaire@dev:~/Desktop/cue 
$ Gaire

Command 'Gaire' not found, did you mean:

  command 'caire' from snap caire (1.4.4)

See 'snap info <snapname>' for additional versions.

rabingaire@dev:~/Desktop/cue 
$ 
```

**Comment by Scorpiion** [comment]
I was able to reproduce this and found the reason for it.

So `cli.Ask` uses `fmt.Scan()` under the hood, and it's using a single string to store the result. `fmt.Scan()` works like this (quote from the docs):

_Scan scans text read from standard input, storing successive space-separated values into successive arguments._

As the Cue code sends in a single string to `fmt.Scan()` it will never "catch/scan" anything else than the first "word" before the space, anything after the space is ignored by the `cue cmd` binary and it is simply entered into the shell when the `cue cmd` has already exited. 

I see two possible solutions here (as I think this is a common use case):

1. Extend `cli.Ask` to support multi word responses
2. Create a new `cli.XXX` command that supports multiple word responses and clarify in docs that `cli.Ask` only works with a single response.

What do you think @myitcv? 

Sources:
- https://github.com/cue-lang/cue/blob/v0.4.3/pkg/tool/cli/cli.go#L67
- https://pkg.go.dev/fmt#Scan

**Comment by mvdan** [comment]
`fmt.Scan`, just like any other form of reading from standard input in an interactive way, will block until a newline is entered. So, from a UX and API point of view, I don't think it makes sense to support a `cli.Ask` that only reads one word, because it blocks until a whole line is entered.

Looking at https://cue-review.googlesource.com/c/cue/+/7261, where the code was reviewed, I don't see that it was a conscious choice to go with `fmt.Scan`. I believe it was an unfortunate choice that didn't get caught during code review :)

I think we should just go with suggestion 1: change `cli.Ask` to read the whole line that it's blocking on. For the sake of backwards compatibility, it's worth noting that `fmt.Scan` skips whitespace before and after the word being read. I think we do want `cli.Ask` to strip the trailing newline, because most users will want `some answer` rather than `some answer\n`.

It's less clear whether we want to keep the trimming of whitespace, so that answering with ` foo ` results in `foo`. I lean towards `cli.Ask` giving the whole line as it was written by the user, including all whitespace except the trailing newline. The CUE command can always strip whitespace via https://pkg.go.dev/cuelang.org/go/pkg/strings#TrimSpace, or get the whitespace-separated words (fields) via https://pkg.go.dev/cuelang.org/go/pkg/strings#Fields.

**Comment by mvdan** [comment]
I forgot to mention the most important point about backwards compatibility: would this change break any CUE commands? I'm inclined to say not, because any existing `cli.Ask` users who just want one word are still ending up with very confusing command-line UX for the end user. They can always use `strings.Fields` to split the answer line and do whatever they want with any number of entered words, for example, and that should work much better.

But this change would certainly warrant a mention in the changelog.

**Comment by myitcv** [comment]
@rabingaire thanks for raising this, and @Scorpiion thanks for the analysis. 

> I lean towards `cli.Ask` giving the whole line as it was written by the user, including all whitespace except the trailing newline

@mvdan: 100% agree with your summary and proposal.

**Comment by mvdan** [comment]
https://review.gerrithub.io/c/cue-lang/cue/+/541426 is my proposed fix per the discussion above, if any of you want to give it a try or a review.
