### ISSUE TITLE
cmd/cue: cmd hangs waiting for input

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1825]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20220729051708-0a46a1624353

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 0a46a1624353da7327d356040a5612251e01659f
        vcs.time 2022-07-29T05:17:08Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Not `@latest`, but with `@master`.

### What did you do?

Note: this example must be run interactively in a terminal, and not via `cmd/testscript` or similar:

```
-- x_tool.cue --
package p

import (
	"tool/exec"
)

command: printer: {
	first: exec.Run & {
		cmd: ["echo", "test"]
	}
}
```

Run:

```
cue cmd printer
```

### What did you expect to see?

Output as follows, and `cue cmd` exiting with a zero exit code.

```
test
```

### What did you see instead?

The following output is printed to the console:

```
test
```

but `cue cmd` never exits.

Bisected to 4432aa66244b1c704143327709741edfc803cc82.

cc @mvdan

**Comment by mvdan** [comment]
Thanks for the report; I can reproduce. It seems like `os/exec` hangs on copying from stdin. Interestingly enough, entering a single newline is enough to unblock the command.

**Comment by mvdan** [comment]
I narrowed it down to https://github.com/golang/go/issues/7990, a known limitation of `os/exec`. In short, when `os/exec.Cmd.Stdin` was a `*os.File` before - `os.Stdin` - the file handle was passed directly to the child process. Now that `os/exec.Cmd.Stdin` is a `*bufio.Reader`, we don't have a file descriptor, so an `io.Copy` happens in Go, via a separate goroutine.

https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/os/exec/exec.go;l=254-274

This is usually fine, except that `os/exec.Cmd.Wait` now has to wait for the `io.Copy` goroutine to finish when the child process exits, and our copy goroutine is blocked on an `os.Stdin.Read` call - since the copying happens in Go code now. And the only way to unblock that read call is by letting the read syscall finish with some result: by either inserting a newline, or entering `^D` as an EOF on stdin.

I honestly forgot that this is a limitation of `os/exec` when `Stdin` is not an `*os.File`. I think going with a `*bufio.Reader` was a mistake, because there's no way to avoid the regression that you've spotted in a nice way.

I think the only reasonable solution is to drop the `*bufio.Reader` entirely, and instead have `cli.Ask` read its input one byte at a time, just like `fmt.Scan` used to do before my previous commit. We would also drop the `sync.Mutex` on all read operations, because we would have to pass `os.Stdin` around directly to `exec.Run`. So we would revert to all the logic races that existed before, but at least we would avoid this interactive CLI regression. And that seems like the right approach, because the example you posted isn't wrong in any obvious way.

Does that sound good to you, Paul?

**Comment by mvdan** [comment]
I also looked at two libc implementations (musl and uclibc) and they both implement `readline` and `readdelim` (equivalent to our usage of `bufio.Reader.ReadString`) by reading one byte at a time. So I think us doing the same is consistent with how most other C-like programs will read one line of input interactively.

**Comment by myitcv** [comment]
Sounds good to me. Thanks for the analysis
