### ISSUE TITLE
cmd/cue: -i / --ignore does not work as shown in tutorials

### ISSUE THREAD

**Issue by sawyer-shieldai** [cue-lang/cue#1981]
Using `cue version v0.4.3 linux/amd64` , copy-pasting .cue files from tutorials and running `cue eval -i` or `cue export -i` does not ignore errors. For example:

bottom.cue
```
a: 4
a: 5

l: [ 1, 2 ]
l: [ 1, 3 ]

list: [0, 1, 2]
val: list[3]
```

_cue eval -i bottom.cue_

Expected:
```
list: [0, 1, 2]
a: _|_ 
l: [1, _|_,
]
val: _|_ 
```

Actual:
```
a: conflicting values 5 and 4:
    ./bottom.cue:1:4
    ./bottom.cue:2:4
l.1: conflicting values 3 and 2:
    ./bottom.cue:4:9
    ./bottom.cue:5:9
val: index out of range [3] with length 3:
    ./bottom.cue:8:11
```

**Comment by myitcv** [comment]
This issue was ported over from cuelang.org. 

Thanks for raising, @sawyer-shieldai. 

Per https://github.com/cue-lang/cue/issues/1786#issuecomment-1226970871, this broke as far back as https://github.com/cue-lang/cue/commit/7f52c107b61980629c4c0d6751386a8ce360ddb9, but the failures in the tutorial were masked by 3e624504bbdd6ca150dca6c4748b9d4e385396c6. 

A straightforward reproducer of the issue with `cue eval -i` follows.

### What version of CUE are you using?

```
$ cue version
cue version v0.0.0-20221116123046-1d8d8ffea6b9

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 1d8d8ffea6b95e2b0d555bd6999004268eb14d16
        vcs.time 2022-11-16T12:30:46Z
    vcs.modified false
```

### What did you do?

```
exec cue eval -i x.cue
cmp stdout stdout.golden

-- x.cue --
a: 4
a: 5

l: [ 1, 2]
l: [ 1, 3]

list: [0, 1, 2]
val: list[3]
-- stdout.golden --
list: [0, 1, 2]
a: _|_ // conflicting values 4 and 5
l: [1, _|_, // conflicting values 2 and 3
]
val: _|_ // index 3 out of bounds
```

### What did you expect?

Passing test.

### What did you see instead?

```
$ ts repro.txtar
> exec cue eval -i x.cue
[stderr]
a: conflicting values 5 and 4:
    ./x.cue:1:4
    ./x.cue:2:4
l.1: conflicting values 3 and 2:
    ./x.cue:4:9
    ./x.cue:5:9
val: index out of range [3] with length 3:
    ./x.cue:8:11
[exit status 1]
FAIL: /tmp/testscript79192004/repro.txtar/script.txtar:1: unexpected command failure
```
