### ISSUE TITLE
cuelang.org: Show cue version number in docs

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1985]
_Originally opened by @jugaadi in https://github.com/cuelang/cuelang.org/issues/178_

With lot of language proposals in pipeline, it would be better if cue version is shown in the docs. This can also help users access the docs of previous versions.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cuelang.org/issues/178#issuecomment-847126240_

This is a great suggestion. Whilst it could be implied that the docs reflect `cuelang.org/go@latest`, being explicit would be much clearer (especially when it comes to https://tip.cuelang.org/)

**Comment by myitcv** [comment]
This has been almost entirely superseded by the new site which makes clear the version number on a given page if it differs from latest. We also have a banner across the bottom of the page which flags the default version of CUE used on the site. The thinking being that once we address https://github.com/cue-lang/cue/issues/2538 then people should be able to rely on the latest (non-prerelease) version of CUE, unless otherwise flagged on a page.
