### ISSUE TITLE
Memory Leak in `load.Instances`

### ISSUE THREAD

**Issue by alecholmez** [cue-lang/cue#2121]
### What version of CUE are you using (`cue version`)?

- v0.5.0-beta.1
- Also tested with v0.4.3

### Does this issue reproduce with the latest release?

Yes it does.

### What did you do?

[test.tar.gz](https://github.com/cue-lang/cue/files/10068351/test.tar.gz)
I've attached a tarball to this issue. We are calling `load.Instances` in a loop
since we need to continuously read changes from the file system.

To reproduce:
-  simply download that tarball 
- run `go run main.go`
- open a browser to `localhost:6060/debug/pprof`. 
- Refresh a few times

You will see the heap constantly go up without garbage collection.
In our production system this is greatly accelerated due to the size of our CUE repo 
but it is fully reproducible with the small example provided above.

### What did you expect to see?

No memory leak.

### What did you see instead?

A release of the memory held on by `load.Instances`.

**Comment by rogpeppe** [comment]
The problem here is that global `cue.Context`, because it holds onto the `*build.Instance` values that you're expecting to be garbage collected.

Here's a log of some stats (map lengths) of some fields inside the `cuectx` value as it progresses through the loop in your example code:

```
loaded: 0; imports: 1; importsByPath: 1; importsByBuild: 1; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 2; importsByPath: 1; importsByBuild: 2; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 3; importsByPath: 1; importsByBuild: 3; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 4; importsByPath: 1; importsByBuild: 4; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 5; importsByPath: 1; importsByBuild: 5; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 6; importsByPath: 1; importsByBuild: 6; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 7; importsByPath: 1; importsByBuild: 7; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 8; importsByPath: 1; importsByBuild: 8; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 9; importsByPath: 1; importsByBuild: 9; builtinPaths: 30; builtinShort: 30; typeCache: 0
loaded: 0; imports: 10; importsByPath: 1; importsByBuild: 10; builtinPaths: 30; builtinShort: 30; typeCache: 0
```

Note the ever-increasing values of `imports` (of type `map[*adt.Vertex]*build.Instance`) and `importsByBuild` (of type `map[*build.Instance]*adt.Vertex`).

For now, the only reasonable workaround is to avoid using the global `*cue.Context` instance, I'm afraid.

**Comment by alecholmez** [comment]
This did in fact end up fixing our issue. Thank you for pointing us in the right direction. We've also noted that in `0.5.0-beta.2` that our memory usage with CUE is much lower so awesome work all! 

Should we close the issue or leave this open for further investigation if this is something that we want to tackle in a future release @rogpeppe @myitcv?

**Comment by Nexucis** [comment]
Hello,

We are facing the same issue. We already avoid to use a global context, and the memory leak is still present even if it's at much lower rate.

The code here: https://github.com/perses/perses/blob/main/internal/api/schemas/loader.go#L76 is called periodically and it is taking days indeed to see the instance crashing due to OOMKilled but it's happening.

I have also run pprof on the heap and it seems calling `load.Instances` is increasing the number of object on the heap:

![profile001](https://github.com/cue-lang/cue/assets/4548045/cd4a5741-b55f-475a-b03d-d39c228116b3)


Prometheus graph:

<img width="1496" alt="image" src="https://github.com/cue-lang/cue/assets/4548045/3d20ee7c-4f2f-40ef-bcb1-8c9793f99fc4">

The flat line of the left was when I deactivated the piece of code shared above. Once it is reactivated we can see the number of object on the heap increasing

**Comment by Nexucis** [comment]
Also, it would be great to no consider this issue as "documentation", but as a bug if possible :)

**Comment by myitcv** [comment]
> Also, it would be great to no consider this issue as "documentation", but as a bug if possible :)

Agreed. 

We also should revisit this given this issue was raised some time ago. And changes from @mvdan to improve the state of loading have landed since.

**Comment by Nexucis** [comment]
cool thank you @myitcv !

FYI, on our side we are using the last stable version (v0.8.1). I didn't try the v0.9 as looking at the changes on this method doesn't seem it will fix / improve this issue.
But I can give a try if you want

**Comment by Nexucis** [comment]
Adding more context here in case it helps.

### Loading cue schemas with a fresh context

On [Perses](https://github.com/perses/perses), we are loading cue schemas to validate later piece of json data. So far nothing incredible.

As stated above calling periodically `load.Instances` is leaking even without the usage of a global context.
Trashing the context used to store the instances, each time we are reloading the schema, helps a bit to decrease the leak.

Seeing that, we decided to stop the reload of the schema to prevent this leak until there is a solution.
And actually the leak is still there 🤯 

### Validating data

The context created in the first step, needs to be stored to be able to later compile the piece of json to be validated. Otherwise it seems it just doesn't work. That's at least what I have observed in my research.

First thing to do to be able to validate a JSON, is we need to call `ctx.CompileBytes()`. 
In case you are interested, the code that is validating the data is here : https://github.com/perses/perses/blob/main/internal/api/schemas/schemas.go#L239-L243

And if you are looking at the `pprof` images shared in my previous post, you will see what actually is leaking is this particular method `ctx.CompileBytes`. 

Which explains on my side why the leak is still there.

### Summarise 

To prevent this leak, currently we need: 
- to load only once the schemas
- somehow used a copy of the context created at step 1 each time we want to validate a JSON.

BUT, so far the only way to create/copy the context is to reload the schemas. 
I didn't find the way to create a copy of the context that I could later trash once the data are validated. So I guess I am doomed 😓 

### Prometheus monitoring

<img width="1251" alt="image" src="https://github.com/cue-lang/cue/assets/4548045/e20c1430-0cd0-4551-8d8a-22e768004b51">

On the left, first line that is increasing slowly is when I was reloading the cue schemas (and creating a new context to replace the old one) every 5min

On the right, the line that increased faster is after deactivating the reload of the schema and I was only validating JSON (every 1 hour because we are provisioning data like dashboard)

I hope it helps a bit and perhaps you know a temporary workaround.

I have already tried to understand why calling only `load.Instances` is leaking even if nothing is stored, but I didn't get or see how it's even possible since ist doesn't seem there is global variable used in cuelang.

**Comment by mvdan** [comment]
Thank you for the added details, @Nexucis. I can indeed confirm I see a memory leak. It appears related to how we load `cue.mod/module.cue` files since we started implementing the new modules experiment; we use our own global `module.cue` schema alongside its cuecontext, and we also use that cuecontext to build the user's module.cue file to verify against. This, unsurprisingly, means that we hold onto a user's` cue.mod/module.cue` file forever in the global state, much in the same way that the original poster in this thread was holding a global `cue.Context` and reusing it forever.

**Comment by mvdan** [comment]
@Nexucis could you please try the latest master (https://github.com/cue-lang/cue/commit/91eec1b616cadd9a67729e2ed0cdc347d24bf92a) and let us know whether you still experience a memory leak?

**Comment by Nexucis** [comment]
sure, let me try it !
Thanks for the quick fix @mvdan

**Comment by Nexucis** [comment]
@mvdan for me it's working fine now with the commit you linked ! The code is running every 15s and I didn't see any big increase like it was the case before. Looks  good to me ! 

<img width="936" alt="image" src="https://github.com/cue-lang/cue/assets/4548045/4fa31e7b-ddc3-4d45-a93a-da9ed77c2c1d">

**Comment by mvdan** [comment]
Excellent, thank you :) I will close this issue as fixed then. Your leak wasn't the same as the original user's, but it was a leak caused by our code nonetheless, so the issue title very much applied.
