### ISSUE TITLE
github: README on "homepage" showed passing tests when CI was actually failing

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2138]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
n/a
</pre>

### Does this issue reproduce with the latest release?

n/a

### What did you do?

Visited https://github.com/cue-lang/cue when 121894c5c4616bc972b60e484989cab321b75800 was at tip.

Looked at the top of the README:

<img width="929" alt="Screenshot 2022-11-24 at 17 37 50" src="https://user-images.githubusercontent.com/3374574/203841575-7a5aee86-08fe-4670-9c39-a830981088df.png">

Saw green passing tests.

Looked towards the top of the page at the commit id:

<img width="906" alt="Screenshot 2022-11-24 at 17 38 40" src="https://user-images.githubusercontent.com/3374574/203841710-e96f9125-7853-4a03-a5a8-591618ec785b.png">

Saw the commit had a red X next to it. Here are the failing CI runs:

https://github.com/cue-lang/cue/actions/runs/3542426042/

### What did you expect to see?

Consistency between the two icons.

### What did you see instead?

As above. Passing tests according to the README icon, failing tests according to the marker next to the commit.

**Comment by myitcv** [comment]
@mvdan please can you take a quick look at this?

**Comment by mvdan** [comment]
Worth noting that, even though the badge is fixed to work like it did before, the two status colors are not actually the same. The badge only tracks the latest TryBot result in master, whereas the green tick on the last commit is only green when _all_ the workflow jobs on the last commit are green. That includes "triggers on push to tip", for example, but may also include a "do a release" job if a commit was also tagged.

I think we're fine with that, because in general it's only the TryBot job that may cause failures. But I wanted to make this note in case we're confused again in the future. I haven't found a way to create a badge that tracks _all_ workflow files - the docs only show how to show the result for one workflow.
