### ISSUE TITLE
cmd/cue: cue help does too much work

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2161]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221128094749-4fee020034c6

      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 4fee020034c66d74c2a0d68d56c72f7728bd8ea3
        vcs.time 2022-11-28T09:47:49Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Create the following testscript, say `slowhelp.txtar`:

```
exec sh -c 'echo package foo > x.cue; yes "x: {a: 1, b: 2, c: \"hello\"}" | head -10000 >> x.cue'
exec cue help
```

Run it as: 
```
time testscript slowhelp.txtar
```

### What did you expect to see?

A fairly quick execution time.

### What did you see instead?

```
2.28user 0.08system 0:02.18elapsed 108%CPU (0avgtext+0avgdata 62404maxresident)k
15400inputs+560outputs (60major+19078minor)pagefaults 0swaps
```

It took over 2s to run `cue help`. If there's no cue file in the directory where `cue help` is running,
the runtime is under 100ms.

In general, invoking `cue help` should not depend on the content of the current directory.

**Comment by mvdan** [comment]
I just realised that this is on purpose, because `cue cmd foo` also works as `cue foo`, so `cue help cmd` is trying to be... helpful by first loading the current package to find all defined CUE commands, so that they can be added to the help output.

For example, emphasis mine:

```
$ cd internal/ci
$ cue help cmd
[...]
Usage:
  cue cmd <name> [inputs] [flags]
  cue cmd [command]

Available Commands:
  gen         gen.workflows regenerates the GitHub workflow Yaml definitions.
[...]
```

However, I don't think this extra work affects commands like `cue -h` or `cue help`, so we could probably narrow it down.
