### ISSUE TITLE
cue/def: running def on the output creates increasingly nested results

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#2251]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.5

go version go1.19.3
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### What did you do?

```
exec cue def 1.cue --outfile 2.cue
exec cue def 2.cue --outfile 3.cue
exec cue def 3.cue
cmp 3.cue golden.output

-- 1.cue --
package main

import "hof.io/repro/foo"

foo.#Foo

a: "A"

-- foo/foo.cue --
package foo

#Foo: {
	a: string
}

-- cue.mod/module.cue --
module: "hof.io/repro"

-- golden.output --
package main

import "hof.io/repro/foo"

foo.#Foo
a: "A"
```

### What did you expect to see?

the final output is the same as the original

### What did you see instead?

```
package main

import "hof.io/repro/foo"

_#def
_#def: {
        _#def
        foo.#Foo
        foo.#Foo
        _#def: {
                _#def
                _#def: {
                        foo.#Foo
                        a: "A"
                }
        }
        a: "A"
}
```

**Comment by mvdan** [comment]
Does this happen with v0.4.3? That's what the section about "latest release" in the bug template is for.

**Comment by verdverm** [comment]
With v0.4.3

```
package main

import "hof.io/repro/foo"

_#def
_#def: {
        _#def
        _#def: {
                _#def
                _#def: {
                        foo.#Foo
                        a: "A"
                }
        }
}
```

While cleaner, I would still consider this undesirable output

**Comment by myitcv** [comment]
@verdverm - just to confirm, is the intent behind embedding `foo.#Foo` into package `main`, to enforce that package `main` should then satisfy `foo.#Foo`?

If so, this gets close to needing what we want in #575 (or similar): a mechanism by which we can enforce that a package value satisfies a given schema. Because the problem with embedding (as in this case) is that closedness is relaxed during the embedding... which is almost certainly not what was intended.

The current behaviour of `def` is to apply some sort of heuristic that guesses what the user was trying to do. If we implement something like `must()` (bike shedding on name and semantics) that heuristic can go away entirely.
