### ISSUE TITLE
cue/load: hangs when importing a package with the same name as the current package

### ISSUE THREAD

**Issue by uhthomas** [cue-lang/cue#2284]
### What version of CUE are you using (`cue version`)?

Installed with [pacman](https://archlinux.org/packages/community/x86_64/cue/), current version `0.4.3-1`.

There's an open issue to resolve this: https://bugs.archlinux.org/task/77648

<pre>
$ cue version
cue version (devel) linux/amd64
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

```
-- cue.mod/module.cue --
module: "example.com"

-- a/a/a.cue --
package a

some_field: "some value"

-- a/a.cue --
package a

import "example.com/a/a"

some_other_field: a.some_field
```

Then run `cue export`.

### What did you expect to see?

Should export successfully.

### What did you see instead?

Infinitely hangs.

**Comment by mvdan** [comment]
Potentially related to https://github.com/cue-lang/cue/issues/849. Likely not an exact duplicate, but both are infinite cycles when importing packages.

**Comment by bozaro** [comment]
Looks like package contains all files with same package name in all ascending directories in this module (don't ask me why): https://github.com/cue-lang/cue/blob/adbe80e41254ff45dfb3194f930db9898e1a7a47/cue/load/import.go#L138-L178
For example, package `example.com/a/b/c/a` will contains all files with `package a` from directories `./a/b/c/a`, `./a/b/c`, `./a/b`, `./a` and `./`.

In this case in packge `example.com/a/a` we got files `a/a/a.cue` and `a/a.cue`. File `a/a.cue` try import itself `import "example.com/a/a"`.

**Comment by mvdan** [comment]
> Looks like package contains all files with same package name in all ascending directories in this module (don't ask me why):

Correct, that's explained in https://cuelang.org/docs/concepts/packages/#instances.

The fact that this example makes `cue/load` hang up is certainly a bug. I can't really convince myself what the right behavior would be, though.

In the original example, one can see the package `a/a` as having an implicit dependency on `a`, since `a/a` inherits the constraints from `a`, per the documentation I linked to. Then, `a` importing `a/a` seems to be what is causing an import cycle that we don't catch, causing the infinite loop.

One option would be to catch this like we already do with import cycles, resulting in an error. This is probably the simplest solution, but I'm not sure if it would break any reasonable use case.

**Comment by mvdan** [comment]
> I'm not sure if it would break any reasonable use case.

That point makes no sense, actually. There can't be any reasonable use case if it currently leads to a hang :)

So it seems to me like we should indeed treat this as an import cycle. @uhthomas would you like to send a patch with a test for this? Or perhaps @bozaro, since you sent a very similar patch recently?

**Comment by bozaro** [comment]
Import cycle error was merged to master https://github.com/cue-lang/cue/commit/220b44e973eff9d41f2067499f20a12b6a0a6f29

**Comment by uhthomas** [comment]
Is it an import cycle? Is it possible to refer to the current package by name? If not, then it should be fine to import another package with the same name.

**Comment by verdverm** [comment]
You might need to rename the import, it's at least best practice. I know you can do this in Go, but it can get very confusing what package you are using when looking at the code.

```cue
package bar

import (
  foobar "domain.com/foo/bar"
)
```

**Comment by mvdan** [comment]
You're right @bozaro, your recent commit seems to have fixed this issue as well. We just forgot to mark it with a "fixes" referencing this issue as well :)

For reference, the script I used to verify the fix was:

```
exec cue export ./...

-- cue.mod/module.cue --
module: "example.com"

-- a/a/a.cue --
package a

some_field: "some value"

-- a/a.cue --
package a

import "example.com/a/a"

some_other_field: a.some_field
```

This finishes with CUE master (204665cebd9623467e6f53cada8e563829ecfeb6), but hangs with v0.6.0.
