### ISSUE TITLE
Evaluating a regular expression produces invalid value error

### ISSUE THREAD

**Issue by behnazh-w** [cue-lang/cue#2291]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.3
</pre>

### Does this issue reproduce with the latest stable release?
yes

### What did you do?

The regular expressions, including [the tutorial example](https://cuetorials.com/overview/expressions/) produce `invalid value` error:
https://cuelang.org/play/?id=yvl4RiGcnGe#cue@export@json

### What did you expect to see?
```
a:         "hello world"
b:         "hello"
lowercase: =~"^[a-z]+$"
c:         "hello"
```

### What did you see instead?
```
e: invalid value "foo bar" (out of bound =~"^[a-z]{3}$"):
    -:4:4
    -:9:4
    -:10:4
``

**Comment by slewiskelly** [comment]
This is correct:

```
e: invalid value "foo bar" (out of bound =~"^[a-z]{3}$")
```

As `"foo bar"` does not match just three lower case characters.

Changing `e: "foo"` removes this error, as expected. However, you will be shown another error, which is also valid:

```
c: incomplete value =~"^[a-z]{3}$":
    -:4:4
```

You can fix this, either by making it a [definition or hidden field](https://cuelang.org/docs/references/spec/#definitions-and-hidden-fields). Making a fully working example of:

```cue
a: "foo bar" =~ "foo [a-z]{3}"
b: "maze" !~ "^[a-z]{3}$"

#c: =~"^[a-z]{3}$" // any string with lowercase ASCII of length 3

d: #c & "foo"

e: #c & "foo" // Changing to "fooo" or "foo bar" will expectedly cause an error.
```

The Cuetorials example is also working as expected, but would show a similar error if `d` was valid according to the regex:

```
lowercase: incomplete value =~"^[a-z]+$":
    -:5:12
```

It would be fixed in the same way:

```cue
a: "hello world" & =~"^hello [a-z]+$"
b: "hello" & !~"^[A-Z]+"

#lowercase: =~"^[a-z]+$"

c: "hello" & #lowercase
d: "Hello" & #lowercase // error
```
