### ISSUE TITLE
evaluator: doesn't properly reject an alias named `_`

### ISSUE THREAD

**Issue by nicuveo** [cue-lang/cue#2381]
### What version of CUE are you using (`cue version`)?

the playground (v0.5.1-0.20230413144408-f681271a38ec and v0.6.0-alpha.1.0.20230428121230-80d6ea032057)

### What did you do?

```cue
_ = a: 3
b: _
```

### What did you expect to see?

Either `_` is a valid alias, and i would therefore expect:

```cue
a: 3
b: 3
```

or `_` is not a valid alias, and i would therefore expect an error that reads `cannot use _ as alias`, similar to the `cannot use _ as label` error.

### What did you see instead?

```
unreferenced alias or let clause _
```

The `_` in b in interpreted as _top_, and the alias is therefore unusable.

### Sidenotes

As a first sidenote, this also demonstrates a behaviour that is not documented in the specification:  the fact that all aliases (and let clauses) MUST be used. The phrasing of [the Aliases section](https://cuelang.org/docs/references/spec/#aliases) suggests that this wasn't originally the case? (emphasis mine)

> Aliases name values that **CAN** be referred to within the scope in which they are declared. The name of an alias **MUST** be unique within its scope.

Furthermore, this restriction that aliases must be unique within their scope doesn't seem to hold anymore either, which also suggests that this part of the documentation is outdated? For instance, the following is valid:

```cue
z = a: {
  z = b: 0
  c: z
}
b: z
```

**Comment by mvdan** [comment]
Thanks for filing this issue! FYI, https://review.gerrithub.io/c/cue-lang/cue/+/556985 will fix the compiler to reject underescore aliases and lets just like it already did for labels.

You mention two other likely discrepancies between the spec and the implementation, relating to "aliases must be used" and "aliases must be unique within their scope". I've split those into https://github.com/cue-lang/cue/issues/2506, so that we can track those spec discrepancies separately from the underscore fix.
