### ISSUE TITLE
cuelang.org: test the code example published at docs/concept/schema-definition-use-case

### ISSUE THREAD

**Issue by rudifa** [cue-lang/cue#2430]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

From the doc page [Schema Definition](https://cuelang.org/docs/usecases/datadef/), I reproduced the code sample given under **Validating backwards compatibility** in a small go program. 

To get it to compile:
- added `var r cue.Runtime`
- pasted `"the following versions of the same API"` text into a `const schema =` `...`
- added the 2nd argument to the call `r.Compile("apis", schema)`
- removed the extra trailing `)` from the 2 `fmt.Println(...)` calls

### What did you expect to see?

```
true
false
```

### What did you see instead?

```
true
true
```

### Next, replaced the comments by `log.Fatal(err...)` which revealed the problem:

```
main.go:76: field not found field not found field not found
exit status 1
```
### Finally, added the missing `#` in the 3 calls `inst.LookupField("#V1")`, e.t.c. and saw the expected

```
true
false
```

### Here is the completed exercise:

```
func main() {
	var r cue.Runtime
	inst, err := r.Compile("apis", schema)
	if err != nil {
		log.Fatal(err)
	}
	v1, err1 := inst.LookupField("#V1")
	v2, err2 := inst.LookupField("#V2")
	v3, err3 := inst.LookupField("#V3")
	if err1 != nil || err2 != nil || err3 != nil {
		log.Fatal(err1, err2, err3)
	}

	// Check if V2 is backwards compatible with V1
	fmt.Println(v2.Value.Subsumes(v1.Value)) // true

	// Check if V3 is backwards compatible with V2
	fmt.Println(v3.Value.Subsumes(v2.Value)) // false
}
```

**Comment by rudifa** [comment]
Besides which, `cue.Runtime is deprecated: use Context.  (SA1019)`... it looks like I am fixing a dying horse.

**Comment by rudifa** [comment]
**Here is the updated version, using only non-deprecated functions:**
```
func main() {
	// ✂ ---------------------------------------------

	ctx := cuecontext.New()

	rootValue := ctx.CompileString(schema)

	v1 := rootValue.LookupPath(cue.ParsePath("#V1"))
	v2 := rootValue.LookupPath(cue.ParsePath("#V2"))
	v3 := rootValue.LookupPath(cue.ParsePath("#V3"))

	fmt.Printf("v1: %#v\n", v1)
	fmt.Printf("v2: %#v\n", v2)
	fmt.Printf("v3: %#v\n", v3)

	// Check if V2 is backwards compatible with V1
	fmt.Println(v2.Subsume(v1) == nil) // true

	// Check if V3 is backwards compatible with V2
	fmt.Println(v3.Subsume(v2) == nil) // false

	// ✂ ---------------------------------------------
}
```

**Comment by myitcv** [comment]
@rudifa thanks for raising this. This is a situation where the current documentation has "gone stale".

We are in the process of building out https://alpha.cuelang.org/, to improve upon and ultimately replace https://cuelang.org/. 

As part of that, I have recently landed some changes for a system we are calling the `preprocessor`. The `preprocessor` helps us write structured documentation that can be tested, just like regular Go/CUE code. 

For example, for the following page explaining the data form of CUE:

https://alpha.cuelang.org/docs/language-guide/data/json-superset/

the source file behind that is:

https://github.com/cue-lang/cuelang.org/blob/alpha/content/docs/language-guide/data/json-superset/en.md?plain=1

You can perhaps see how the structured code blocks make this fully testable. 

Each of the guides with code examples is [regenerated as part of CI](https://github.com/cue-lang/cuelang.org/blob/bebe02e01d419f3ca94176705b64abba096ff7cf/internal/ci/github/trybot.cue#L107).

I am in the process of making changes to support documentation that can run examples using the Go API. As a follow-up to that change landing in the `alpha` branch, I will look to present a rewritten form of this document in which you have found errors, as a way of a) rewriting the example to conform to the current API, but also b) as a way of demonstrating how the `preprocessor` works to ensure documentation does not go stale. 

My suggestion is therefore that we look to make these changes in https://alpha.cuelang.org/ and simply speed up the process of moving to that site, rather than fixing the current site (which is impossible to test in an automated way).

**Comment by rudifa** [comment]
@myitcv Thank you for the detailed response.

Re _simply speed up the process of moving to that site, rather than fixing the current site_ : this makes a lot of sense. 

The future automatic generation of docs and testing of code samples is good news, TIA.

**Comment by myitcv** [comment]
@jpluscplusm I think we're done here?

**Comment by jpluscplusm** [comment]
> @jpluscplusm I think we're done here?

I'm not sure. https://cuelang.org/docs/concept/schema-definition-use-case/ has inherited the content from the old site's  docs/usecases/datadef, but the on-page examples are the versions which this issue calls out as being insufficient/incorrect, and they're stored inside `code` blocks solely for display purposes. I.e. they're not tested.

This page (in common with all the `docs/concept/*-use-case` pages) will get superceded by a friendlier page at some point, but it might be as well for their replacements to build on tested and up-to-date code examples.

**Comment by myitcv** [comment]
Please can you link/create the relevant docs-and-content issues @jpluscplusm ?

**Comment by jpluscplusm** [comment]
@myitcv Please move this issue to `cue-lang/docs-and-content`. I will update/comment to reflect its purpose of making all the code example automatically tested. A review of the on-page code after that (somewhat) mechanical process is tracked in https://github.com/cue-lang/docs-and-content/issues/139, with the aim of reflecting current Go API use.
