### ISSUE TITLE
Confusing error message when running top-level custom command with syntax errors

### ISSUE THREAD

**Issue by mxey** [cue-lang/cue#2547]
When running `cue $CMD` and there are syntax errors in the CUE files, you get the message that no commands are defined, which is misleading. If you run `cue cmd $CMD`, you get the actual syntax errors.

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

testscript:
```
! exec cue cmd build
cmp stderr helpful

! exec cue build
cmp stderr helpful

-- helpful --
missing ',' in struct literal:
    ./build_tool.cue:7:16
expected 'EOF', found '}':
    ./build_tool.cue:11:1
-- build_tool.cue --
package foo

import (
	"tool/cli"
)

command: build {
	task: hello: cli.Print & {
		text: "Hello World"
	}
}

```

### What did you expect to see?

PASS

### What did you see instead?

```
> ! exec cue build
[stderr]
no commands defined
Ensure custom commands are defined in a "_tool.cue" file.
Run 'cue help cmd' to list available custom commands.
Run 'cue help' to see the built-in 'cue' commands.
[exit status 1]
> cmp stderr helpful
diff stderr helpful
--- stderr
+++ helpful
@@ -1,4 +1,4 @@
-no commands defined
-Ensure custom commands are defined in a "_tool.cue" file.
-Run 'cue help cmd' to list available custom commands.
-Run 'cue help' to see the built-in 'cue' commands.
+missing ',' in struct literal:
+    ./build_tool.cue:7:16
+expected 'EOF', found '}':
+    ./build_tool.cue:11:1

FAIL: /var/folders/k_/nbvcnqz17vdc75tz068w33jc0000gp/T/testscript2777027464/cue-repro.txtar/script.txtar:4: stderr and helpful differ
error running cue-repro.txtar in /var/folders/k_/nbvcnqz17vdc75tz068w33jc0000gp/T/testscript2777027464/cue-repro.txtar
```

**Comment by mvdan** [comment]
> If you run `cue cmd $CMD`, you get the actual syntax errors.

If that's the case, I think we should fold this into https://github.com/cue-lang/cue/issues/2519. `cue foobar` loads the `*_tool.cue` files in a different way from `cue cmd foobar`, since we want `cue exprot` (a typo for `cue export`) to fail with "no such command" no matter what, even if there are syntax errors in `*_tool.cue` files, since those wouldn't be loaded by `cue export` or other built-in commands.

We can't really make the errors in the short form significantly better because we don't know if the user intends to run a built-in command or a custom command - that's a CLI design problem we can't really work around, except for deprecating and removing the short form.

**Comment by mvdan** [comment]
I'm going to go ahead and close this in favor of #2519, since I don't see a better way to solve this problem aside from #2519. And we want to deprecate and remove this short form very soon, anyway :) Please say if I missed anything.
