### ISSUE TITLE
preprocessor: additional {{{with sidebyside}}} heuristic for 1 or 2 files and a command

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2601]
The following alternative heuristic, applied to the contents of `sidebyside`'s txtar, should allow for multiple pieces of content to have their layouts controlled by the preprocessor.

In addition to the existing `in/out` heuristic, this Issue requests a single additional form, with 2 implicit options requiring a single  layout choice to be made by the preprocessor.

## 1 or 2 files with explicit command

heuristic: apply this when either 1 or 2 files are present, along with a command in the txtar comment.

Place the contents of the first file encountered in the top-left area. Its display title is the filename as presented. Its copy-content button copies the content, as presented. It has a code block language inferred from the filename suffix, or `text` if it's CUE (because of highlighting+line numbers being broken currently), or no language if the filename suffix doesn't allow us to infer anything.

Place the contents of the second file encountered in the top-right area, with identical handling to the first. A second file is optional, hence might be missing.

The txtar comment represents the command to be run. It is a testscript `exec` line, which permits expected command failure with a `!` prefix. The command's display title is the command's string, with its testscript-related prefix removed, and a dollar-space (`$ `) prefix added. The command's copy-button's content is the command string, with its testscript-related prefix removed. 

If there's only a single file present, place the command in the top-right area. Otherwise, place it in the bottom area.

### Example with 2 files

Rendered: https://cl-1167621-11--cue-cls.netlify.app/docs/howto/mark-a-field-as-optional/

Txtar imagined by this Issue:

```
! exec cue vet .:example data.yml
-- example.cue --
package example

// CUE indicates optional fields
// with a question mark: "?"

// f1 is optional.
// if it's present it can be
// any value

f1?: _

// f-2 is optional.
// if it's present it must be
// a string

"f-2"?: string

// s1 is a regular field
// containing a struct which will
// be present no matter what the
// input data contains

s1: {
	// f3 is optional.
	// if it's present it
	// must be an integer
	// less than 10

	f3?: int & <10
}
-- data.yml --
# f1 is a nested struct
f1: 
  f1.1:
    f1.2: some string

# f-2 is floating point number,
# not a string
f-2: 42.137

# s1 only contains the field x,
# not f3.
s1:
  x: some other string
```

## Example with 1 file

Rendered: https://cl-1167624-5--cue-cls.netlify.app/docs/howto/specify-a-default-value-for-a-field/#defaults-are-usually-specified-as-concrete-values

Txtar imagined by this Issue:

```
! exec cue export .:example
-- example.cue --
package example

a: *"A" | _
b: *string | _
```

**Comment by myitcv** [comment]
Couple of observations:

1. We need to vocalise "2 files" as "3 panes", because that's what will be rendered. Indeed, the `txtar` input will also capture the result, so there will be 3 files there too. So in your description above you're actually referring to 3-file and 2-file respectively.
1. I tend to agree the 3-pane (3-file) version should have the results rendered at the bottom. Not least because of the scenario where we will have error lines, which can be long. We will just have to see how much it jars with the fact that the 2-file version has it on the right.
1. I think we can make the 2-file (by my definition!) version work with and without an explicit command. If a `txtar` does not have an effective comment (i.e. the comment sections is just empty lines or comments) then we can come up with rules for establishing a command based on filenames. We have that already for 2-file archives, the logic might extend to 3. Where there is an effective comment, then we could establish rules for which command we pick. For example we could take the first non-tagged command (there might be multiple in the case that `cmp` is used to verify results etc). The tag would be on the same line as a command, at the end of the line, something like `exec cue export #cmdignore`

**Comment by myitcv** [comment]
Indeed regarding point 3 (I've just edited the previous comment to use numbering instead of bullets) I think we already support almost exactly those semantics:

https://github.com/cue-lang/cuelang.org/blob/alpha/content/docs/language-guide/data/organizing-configuration/en.md?plain=1#L114-L133

Which renders as:

https://alpha.cuelang.org/docs/language-guide/data/organizing-configuration/#packages

**Comment by jpluscplusm** [comment]
The features requested by this issue are now provided by the `{{{with code ...}}}` preprocessor directive.
