### ISSUE TITLE
OneOf pattern does not work for open structures

### ISSUE THREAD

**Issue by megadrifter** [cue-lang/cue#2636]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0

go version go1.20.6
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

</pre>

### Does this issue reproduce with the latest stable release?
YES

### What did you do?
<pre>
#OneOf: {a: string} | {b: string}

#E: {
	#OneOf
        ...
}

ex1: #E & {
	name: "a choice"
	a:    "bar"
}

ex2: #E & {
	name: "b choice"
	b:    "hello"
}
</pre>

### What did you expect to see?
cue vet -c   should not result in errors. 
Should work as JSON Schema with "OneOf" and "additionalProperties": true
<pre>
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": true,
          "required": ["a"],
          "properties": {
            "a": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "additionalProperties": true,
          "required": ["b"],
          "properties": {
            "b": {
              "type": "string"
            }
          }
        }
</pre>

### What did you see instead?
`ex1: incomplete value {name:"a choice",a:"bar"} | {name:"a choice",a:"bar",b:string}
ex2: incomplete value {name:"b choice",b:"hello",a:string} | {name:"b choice",b:"hello"}`

**Comment by selfuryon** [comment]
Playground with an [example](https://cuelang.org/play/?id=zV1mD3_PH2d#cue@export@cue)

**Comment by verdverm** [comment]
I believe #943 covers this

**Comment by myitcv** [comment]
I have just raised https://github.com/cue-lang/cue/issues/3165 to pick up on this in more detail. #943 does indeed discuss a potential solution to encoding oneofs, but the issue I've opened I think raises some necessary points to cover before deciding on the approach outlined in #943. 

On closer reading of _this_ issue, I should probably have repurposed it rather than creating https://github.com/cue-lang/cue/issues/3165. Apologies for the churn - please subscribe to https://github.com/cue-lang/cue/issues/3165 which I think consolidates various threads of conversation.
