### ISSUE TITLE
cuelang.org: frontend: can I search for strings that start with punctuation?

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2640]
**Is your feature request related to a problem? Please describe.**

I'd like to find all docs on alpha.cuelang.org that mention a specific `cue` CLI flag. In this case, `-l`. 

But when I search for `-l`, I get a list of pages all of which have a `L` suspiciously near the start of their title, making me suspect that the search is throwing the punctuation away.

If I add quotes (`"-l"`), the set of pages returned is smaller, and seems to include those where the string is contained mid-word (e.g. "the foo-list is a list of ..."). And whilst this is *technically* correct, it doesn't feel *useful*.

**Describe the solution you'd like**

I'd like:

- a way to search for pages containing strings that start with punctuation when it's a word in its own right. 
- a page/place on the site explaining the search syntax/operators/etc I have available

**Describe alternatives you've considered**

n/a

**Additional context**

I've raised https://github.com/cue-lang/docs-and-content/issues/1 to track the additional page content request, in parallel.

**Comment by JorindeUsMedia** [comment]
Algolia:

> By default, the engine ignores non-alphanumeric characters like hyphen (-), plus (+), and parentheses ((,)). Whether these characters are in the query or the index, Algolia won’t search for them.
This is by design: searching for +33 returns all records with an attribute starting with +33 or 33, because the engine ignores the plus sign (+). If you would like users to search with special characters, you must let the engine know to index these characters. You can do so with [separatorsToIndex](https://www.algolia.com/doc/api-reference/api-parameters/separatorsToIndex/).

https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/how-to/how-to-search-in-hyphenated-attributes/#:~:text=By%20default%2C%20the%20engine%20ignores,won't%20search%20for%20them.

We can add characters using the 'separatorsToIndex' setting: https://www.algolia.com/doc/api-reference/api-parameters/separatorsToIndex/

This is easy to add to the settings. Which characters would you like to support besides '-' ? @jpluscplusm

**Comment by jpluscplusm** [comment]
@JorindeUsMedia Initially, I /believe/ the user need would be to search for:

1. words that begin with single or double hyphens (`-l`, `--path`)
2. word pairs separated by hyphens (`built-in`)
3. word pairs separated by dots (`list.Contains`)
4. word pairs separated by (forward) slashes (`encoding/json`)
5. a mixture of 1 and 2 (`--with-context`)

Paging @myitcv to cross-check my assumptions.
