### ISSUE TITLE
cuelang.org: support links to source files inside packages

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2743]
In https://review.gerrithub.io/c/cue-lang/cue/+/1173892, @rogpeppe wants to link to a file in our source code via https://cuelang.org/go/internal/cueexperiment/exp.go - which is currently a 404, since we simply redirect to https://pkg.go.dev/cuelang.org/go/internal/cueexperiment/exp.go.

pkg.go.dev does not directly have a source code viewer. Instead it shows source file links in https://pkg.go.dev/cuelang.org/go/internal/cueexperiment#section-sourcefiles as e.g. https://github.com/cue-lang/cue/blob/v0.7.0/internal/cueexperiment/exp.go.

It would be nice for `cue help environment` to be able to link to https://cuelang.org/go/internal/cueexperiment/exp.go instead of directly to github via e.g. https://github.com/cue-lang/cue/blob/HEAD/internal/cueexperiment/exp.go. The latter is a longer link, and unnecessarily hard-codes github.com in our documentation, whereas we stick to cuelang.org/issue and cuelang.org/cl redirecting URLs elsewhere.

**Comment by myitcv** [comment]
One thing I'm not clear on here is how we would distinguish links that we want to redirect to pkg.go.dev from those which we want to redirect to GitHub for source viewing. 

As I understand what you're proposing:

* https://cuelang.org/go/internal/cueexperiment should redirect to https://pkg.go.dev/cuelang.org/go/internal/cueexperiment
* https://cuelang.org/go/internal/cueexperiment/exp.go should redirect to https://github.com/cue-lang/cue/blob/master/internal/cueexperiment/exp.go

(Side point: but I think pkg.go.dev could do more here - it has all the information to unambiguously redirect)

**Comment by mvdan** [comment]
Yes, arguably pkgsite should deal with this, but it doesn't, and we have no idea how soon it might.

> One thing I'm not clear on here is how we would distinguish links that we want to redirect to pkg.go.dev from those which we want to redirect to GitHub for source viewing.

We could decide based on whether the path has a `.go` suffix. Not great, but also will cover almost every use case in practice I can think of.

**Comment by myitcv** [comment]
Per offline clarification:

> 

> In https://review.gerrithub.io/c/cue-lang/cue/+/1173892, @rogpeppe wants to link to a file in our source code via https://cuelang.org/go/internal/cueexperiment/exp.go - which is currently a 404, since we simply redirect to https://pkg.go.dev/cuelang.org/go/internal/cueexperiment/exp.go.

I'm not actually clear that @rogpeppe needs/wants to link to a file, because the documentation of the package already appears to suffice:

https://pkg.go.dev/cuelang.org/go/internal/cueexperiment

i.e. it already documents the values that are valid for `CUE_EXPERIMENT` (arguably the docs could be made clearer)

So per our agreement, let's close this because we don't need to link to a file, nor do I think we should given the documentation is effectively already covered at the package level. Hence we'll close this issue and in case we do ever need to link to a file we can push for pkg.go.dev to support that properly.
