### ISSUE TITLE
Weird error/behavior with self-referencing array comprehension.

### ISSUE THREAD

**Issue by chakrit** [cue-lang/cue#2748]
### What version of CUE are you using (`cue version`)?

0.7.0, I built from source

<pre>
$ cue version

cue version v0.0.0-20231206092655-ce1ad81f0aee

go version go1.21.5
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
             vcs git
    vcs.revision ce1ad81f0aee1f88ef12dbf463551f694e8dd906
        vcs.time 2023-12-06T09:26:55Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

```cue
import "list"

import "strings"

#Lower: {
	input:  string
	output: strings.ToLower(input)
}
#Upper: {
	input:  string
	output: strings.ToUpper(input)
}

#Chain: {
	input: string
	filters: [...(#Lower | #Upper)]

	let inp = input

	_values: [...string]
	_values: [
		for idx, filter in filters {
			if idx == 0 {
				(filters[0] & {input: inp}).output
			}
			if idx > 0 {
				(filters[idx] & {input: _values[idx-1]}).output
			}
		},
	]

	output_len: len(_values)
	output_arr: _values
	output:     _values[len(_values)-1]
}

result: (#Chain & {
	input: "Hello World"
	filters: [#Lower, #Upper]
})
```

Run with `cue eval playground.cue`

### What did you expect to see?

`"HELLO WORLD"` as output

If you adds a scoping `-e result` when eval-ing, the output came out correctly. However, if it's omitted, an error is thrown.

### What did you see instead?

```
#Chain.output: index (len(_values) - 1) out of range [-1]:
    ./playground.cue:34:14
    ./playground.cue:34:22
```

---

If we comment out the `output:` field, it seemed to work correctly returning:

```cue
result: {
    input: "Hello World"
    filters: [#Lower & (#Lower | #Upper), #Upper & (#Lower | #Upper)]
    output_len: 2
    output_arr: ["hello world", "HELLO WORLD"]
}
```

Note the `output_len` and `output_arr` are correctly evaluated. Adding the `output` field is what breaks it.

**Comment by perelo** [comment]
Allow me to jump in here.
In my understanding, the confusion comes from the fact that the `#Chain` struct is evaluated independently, regardless that it is only used in `result` with more specific `input` and `filters`. It still needs to be evaluated as is. 
The fact that `-e result` works is precisely because of that, since `#Chain` isn't part of the end result it doesn't need to be fully evaluated.

They may be some issues about self-referencing array comprehensions, but IMO it is not the case here.

So, looking at `#Chain` standalone: `filters` is an *empty* list, so `_values` is also an empty list, and so `(len(_values) - 1) out of range [-1]`.

As a quick fix, I can think of
  * using a disjunction on `output` with a default on the desired result: 
```
output: *_values[len(_values)-1] | input
```
  * or put the whole struct as a named expression:
 ```
let Chain = { ... }
result: Chain & ...
```

**Comment by chakrit** [comment]
>  the confusion comes from the fact that the #Chain struct is evaluated independently

Took me a solid few minutes to figure what you mean by this. Now I understands it. Both quick fixes you gave me works perfectly. Thanks! 🎉 

I had to go with the disjunction solution because converting `#Chain` to `let Chain` changes how it can be accessed (imported and used in other .cue files).

Still think this is a cool use case and it actually let me model a series of composable transformations on a value and maybe cue should have more higher-level (or even first-class) support for these that doesn't require deep understanding (that #Chain will be independently evaluated) to understand how it works. But again, I'm probably using cue a little too far outside of it's initial intended use case, so I guess I'll just have to accept it for now.

---

Closing this issue for now, but I do feel there might still be some fix or enhancement possible to be added to cue here in this area.
