### ISSUE TITLE
cmd/cue: add mod where (or similar) command

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2829]
I went to write a piece of documentation, to complement https://alpha.cuelang.org/docs/tutorial/working-with-a-custom-module-registry/, that explains how `CUE_REGISTRY` can be set to "route" modules from different registries, [per the docs](https://alpha.cuelang.org/docs/reference/cli/cue-environment/).

#2818 captures the changes the would be required as part of the site itself.

When writing such documentation the question arises: "how would I show the user that `$module` routes to `$registry`?"

The answer seems to best be answered by a command like `cue mod where $module` that might work something like this:

```
$ cue mod where my.example/module
my.example/module => https://my.registry.com/modules/my.example/module
```

🚲-shed the naming, but this command feels like it would immediately add value to the documentation.

**Comment by rogpeppe** [comment]
After chatting about this recently, this will need to be clear (somehow!) about the fact that a given package might exist at any module that's a prefix of the package. So without actually consulting the registries in question, `cue mod where` cannot print a definitive location for a _package_ path, even though it can for a _module_ path.

For example, given this registry configuration:
```
moduleRegistries: {
    "example.com": registry: "registry1.example"
    "example.com/foo": registry: "registry2.example"
}
```
the package `example.com/foo/bar` might exist in any of:
- package `foo/bar` in module `example.com` in `registry1.example`
- package `bar` in module `example.com/foo` in `registry2.example`
- the root package in module `example.com/foo/bar` in `registry2.example`

There is no way of telling which without actually going and reading the contents
of the modules mentioned above, because all those modules might exist.

Given that, it seems like `cue mod where` could have two modes, one entirely
lexical where it prints what registry a particular module would be fetched at
if it existed, and another that actually checks the contents and prints out where
a given package does _actually_ exist at with respect to the current module
and dependency versions.

Although perhaps the latter mode might fit better into a `cue list` command.

**Comment by myitcv** [comment]
Working on https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1185680, it becomes very obvious we need something here. Because I want to be able to make clear to the user that, in the absence of any explicit configuration, `registry.cue.works` is the effective registry. And I want to be able to run a command to show that.
