### ISSUE TITLE
Accessing fields of embedded defnition

### ISSUE THREAD

**Issue by r0b3r7137** [cue-lang/cue#2837]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.1

go version go1.22.0
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,panicnil=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

<pre>
import "list"

Network1: [...string] & ["1.2.3.4", "2.3.4.5"]
Network2: [...string] & ["3.4.5.6", "1.1.1.1"]

#Network: {
        ip: string
}

#NetworkX: {
        #Network
        _allowed_ip: list.Contains(Network1, ip) & true
}

MyNetwork: #NetworkX & {
        ip: "1.2.3.4"
}
</pre>

### What did you expect to see?

For a definition like `#Network: {ip: string}`, if writing `#NetworkX: {#Network}` is same as `#NetworkX: {ip: string}`, then I expect `ip` field reference to be available inside `#NetworkX`. Am I misunderstanding the concept of embedding here?

### What did you see instead?

<pre>
$ cue eval t.cue
#NetworkX._allowed_ip: reference "ip" not found:
    ./t.cue:12:39
</pre>

**Comment by mvdan** [comment]
Declarations in CUE are scoped: https://cuelang.org/docs/references/spec/#declarations-and-scope

In your example, `id` is in the `#Network` struct scope, but not in `#NetworkX`. Embedding unifies the values (https://cuelang.org/docs/references/spec/#embedding), but it doesn't join their scopes.

You can solve this by using the `#Network` scope when referencing `ip`: https://alpha.cuelang.org/play/?id=LgMrdQ09eKR#w=function&i=cue&f=eval&o=cue

If you want to avoid repeating the definition name, you can use an alias too: https://alpha.cuelang.org/play/?id=HImrTplemDZ#w=function&i=cue&f=eval&o=cue

Although it's unclear to me why this works with an alias to the struct, when without the alias it doesn't work - both should be using the same scope per https://cuelang.org/docs/references/spec/#aliases:

> Before a value (`foo: X=x`)
> * binds the identifier to the value it precedes within the scope of that value.

**Comment by r0b3r7137** [comment]
That makes sense, thanks.

> Although it's unclear to me why this works with an alias to the struct, when without the alias it doesn't work

I'll keep this open, maybe others have answers on this.

**Comment by myitcv** [comment]
FYI there is rather a nasty CUE bug lurking in this example. I've extracted that to https://github.com/cue-lang/cue/issues/2839

**Comment by myitcv** [comment]
I've also raised https://github.com/cue-lang/docs-and-content/issues/60 to capture what I think would be a very good tutorial for https://alpha.cuelang.org/docs/tutorial/.

**Comment by mvdan** [comment]
> You can solve this by using the `#Network` scope when referencing `ip`: https://alpha.cuelang.org/play/?id=LgMrdQ09eKR#w=function&i=cue&f=eval&o=cue

Please disregard this solution of mine; it doesn't work at all. It only appeared to work because of the bug that Paul mentions, #2839.

The actual solution is to use an alias, like in my second example: https://alpha.cuelang.org/play/?id=HImrTplemDZ#w=function&i=cue&f=eval&o=cue

This is because the alias binds to the value, which is then unified with your concrete `ip`, so the `N.ip` reference ends up resolving to `"1.2.3.4"`.

Paul also correctly pointed out that https://alpha.cuelang.org/docs/concept/alias-and-reference-scopes/ has some examples on the difference between referencing fields via definitions versus aliases, which might be an interesting read.

Given that we've answered your question, raised an issue to track a bug this uncovered, and raised another issue for better docs relating to struct embedding, I think we can close this now as solved :) Thank you!
