### ISSUE TITLE
modules: integration tests vs various OCI registry backends

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2843]
https://github.com/cue-lang/cue/issues/2817 and #2840 both highlight the fact that in reality OCI implementations can vary. This is not really surprising, but for CUE modules users, we should try where possible to limit these surprises.

Introducing some form of integration tests vs various OCI registry backends will help to provide an early flag of a hopefully large subset of problems.

Creating this issue as a placeholder for such tests.

**Comment by mvdan** [comment]
I think this should go in our existing end-to-end test suite in `internal/e2e`; we already cover Google Cloud, which needs a special step to set up the `gcloud` authentication. We could copy a similar mechanism for other registry services.

I suspect we'll need one testscript per service, even if over half of the testscript looks the same, because each service will need its own way to set up auth via a secret, and some may require a custom CUE_REGISTRY config due to e.g. repository name restrictions.

**Comment by myitcv** [comment]
Closing as a dup of #2933
