### ISSUE TITLE
cmd/cue: add 'mod get' to control dependency versions

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2867]
Right now it is only possible to manually edit versions of dependences in the main module (after an initial `cue mod tidy`).

We should look to add something akin to [`go get`](https://go.dev/ref/mod#go-get) to control these versions:

```
# Upgrade a specific module.
$ go get golang.org/x/net

# Upgrade modules that provide packages imported by packages in the main module.
$ go get -u ./...

# Upgrade or downgrade to a specific version of a module.
$ go get golang.org/x/text@v0.3.2

# Update to the commit on the module's master branch.
$ go get golang.org/x/text@master

# Remove a dependency on a module and downgrade modules that require it
# to versions that don't require it.
$ go get golang.org/x/text@none

# Upgrade the minimum required Go version for the main module.
$ go get go

# Upgrade the suggested Go toolchain, leaving the minimum Go version alone.
$ go get toolchain

# Upgrade to the latest patch release of the suggested Go toolchain.
$ go get toolchain@patch
```

**Comment by rogpeppe** [comment]
One significant design decision to be made here: the name `cue mod get` in the issue title seems to imply that this would work at the module level; that is, all arguments would name modules. The Go equivalent, `go get`, works at the package level: its arguments are package patterns.

It could be argued that the Go design is mainly like that for historical reasons (`go get` predates modules support in Go), but that design might also be easier to use, so worth considering.

**Comment by rogpeppe** [comment]
Based on self-anecdotal evidence using `go get`, I'm thinking of a considerably simpler design than `go get` that nonetheless covers almost all the ways I've used it personally:

- arguments are module paths (not package paths), with optional `@version` suffixes.
- if an argument omits a version suffix, it's assumed to be `@latest`
- `@latest` versions are interpreted the same way that `cue mod tidy` already pulls the latest version of a module
- if an explicit version is specified, that will be used _unless_ some existing dependency is already using a higher version (no downgrading).

So, for example:

`cue mod get foo.example/bar` would add the latest version of module `foo.example/bar` to `module.cue` if it didn't already exist, or upgrade it if it did.
`cue mod get foo.example/bar@v0.9.10` would upgrade module `foo.example/bar` to `v0.9.10` or fail with an error if it can't do so because some dependency is already using a later version than that.
