### ISSUE TITLE
modules: Marcel to retrospectively review API changes in v0.8.0-alpha.4

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2896]
- [x] [cuelang.org/go/mod/modcache](https://pkg.go.dev/cuelang.org/go@v0.8.0-alpha.4.0.20240304110036-6cba4c0b2dee/mod/modcache)
- [x] [cuelang.org/go/mod/modconfig](https://pkg.go.dev/cuelang.org/go@v0.8.0-alpha.4.0.20240304110036-6cba4c0b2dee/mod/modconfig)
- [x] [cuelang.org/go/mod/modfile](https://pkg.go.dev/cuelang.org/go@v0.8.0-alpha.4.0.20240304110036-6cba4c0b2dee/mod/modfile)
- [x] [cuelang.org/go/mod/modregistry](https://pkg.go.dev/cuelang.org/go@v0.8.0-alpha.4.0.20240304110036-6cba4c0b2dee/mod/modregistry)
- [x] [cuelang.org/go/mod/module](https://pkg.go.dev/cuelang.org/go@v0.8.0-alpha.4.0.20240304110036-6cba4c0b2dee/mod/module)
- [x] [cuelang.org/go/mod/modzip](https://pkg.go.dev/cuelang.org/go@v0.8.0-alpha.4.0.20240304110036-6cba4c0b2dee/mod/modzip)

**Comment by mvdan** [comment]
@myitcv @rogpeppe I will piggyback on this issue to point out that the new mod packages are exposing a significant amount of API that we might not need at all:

```
$ deadcode ./... | grep '^mod/'
mod/modregistry/client.go:86:6: unreachable func: NewClient
mod/modregistry/client.go:471:25: unreachable func: SingleResolver.ResolveToRegistry
mod/module/error.go:17:6: unreachable func: VersionError
mod/module/module.go:165:6: unreachable func: MustParseVersion
mod/module/module.go:177:6: unreachable func: ParseVersion
mod/module/path.go:483:6: unreachable func: MatchPathMajor
mod/modzip/zip.go:201:6: unreachable func: CheckFiles
mod/modzip/zip.go:369:6: unreachable func: CheckDir
mod/modzip/zip.go:396:6: unreachable func: CheckZipFile
mod/modzip/zip.go:886:22: unreachable func: ZipFileIO.Path
mod/modzip/zip.go:889:18: unreachable func: ZipFileIO.Lstat
mod/modzip/zip.go:892:18: unreachable func: ZipFileIO.Open
```

This method is imprecise, particularly if any of these APIs are called from our existing exported APIs like `cue/load`, then they're not truly dead as we can't remove existing exported APIs. Still, we should go over these one by one - at least from a cursory look, the `modzip` Check APIs are truly unused, as only `CheckZip` is used outside of the tests.

**Comment by mvdan** [comment]
I should note that this is natural given that we inherited a significant amount of code from Go. And we don't currently enforce any "unused code" tooling such as staticcheck or deadcode, which is why I'm running it now. I'd love us to run stuff like that continuously soon, but that's a small project of its own.

Some of these APIs may well be potentially useful to our Go API users, but if we don't need them ourselves to implement modules support in `cmd/cue` and `cue/load`, I very much think we should omit them from our `mod/...` packages until their need is proven.

**Comment by mvdan** [comment]
One more thought: in terms of sequencing, I think it makes sense for us three to do this first thing on Monday, and delete any APIs and code we don't wish to expose (even if experimental) in v0.8.0, before Marcel takes a look later in the day. Otherwise it's a bit of a wasted effort for Marcel to review APIs we don't actually plan to release soon.

**Comment by mvdan** [comment]
Took a stab at it here: https://review.gerrithub.io/c/cue-lang/cue/+/1177674

I ended up deleting only about half of those APIs, as the others didn't seem clearly out of place.

**Comment by myitcv** [comment]
I've just updated the links in the description to refer to v0.8.0-alpha.4.0.20240304110036-6cba4c0b2dee (current tip) following the merge of https://cuelang.org/cl/1177674

**Comment by mvdan** [comment]
Roger and Marcel did this yesterday (March 4th) and it resulted in the changes at https://review.gerrithub.io/c/cue-lang/cue/+/1177702.
