### ISSUE TITLE
cuelang.org: Incomplete value when exporting to JSON/YAML in CUE playground

### ISSUE THREAD

**Issue by willramirezdev** [cue-lang/cue#2936]
### What version of CUE are you using (`cue version`)?
0.7.1 in playground

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

See CUE [playground exmaple](https://cuelang.org/play/?id=QqfAXey5iwc#cue@export@json)

CUE:
```
#uriSchema: {
    uri: string
}

#ipSchema: {
    ip: string
}

#resource: #uriSchema | #ipSchema


config: [string]: {
    resource: #resource
}

config: cue: {
    resource: {
        uri: "https://cuelang.org"
    }
}
```

### What did you expect to see?
Correctly exported YAML for this CUE output:
 
 ```
 config: {
	cue: {
		resource: {
			uri: "https://cuelang.org"
		}
	}
}
 ```

### What did you see instead?
```
config.cue.resource: incomplete value {uri:"https://cuelang.org"} | {uri:"https://cuelang.org",ip:string}

```

**Comment by myitcv** [comment]
Thanks for raising, @willramirezdev. https://github.com/cue-lang/cue/issues/2417 is a previous instance of where the playground behaved differently to `cmd/cue` in case that helps with our investigation.

**Comment by dfinkel** [comment]
Here's a more minimal repro:
https://cuelang.org/play/?id=uGLGUrnM-cv#w=function&i=cue&f=export&o=yaml
```cue
_#fizzlebit: {a: string, ...} | {b: string, ...}
abc: _#fizzlebit & {
        a: "abcde"
}
```


I haven't dug into the code enough to be sure (and I definitely am no where near a fix), but it seems that `Validate` is failing to eliminate alternatives in a disjunction aren't can't be concrete, thus reporting an error, when one of the alternatives is perfectly valid and matches, but the other has an unmet requirement (in these examples, a field that's unset).

This isn't just a bug in the playground. It's a bug in anything that calls [`validate.Validate()`](https://github.com/cue-lang/cue/blob/d8e69536e5ed3e00014880fa09f03767542b6e62/internal/core/validate/validate.go#L97-L99). `cue eval` (and the equivalent playground mode) don't make that call.
 
This is pretty easy to repro with `cue vet`.


Running at current `master`:
```sh
% cat /tmp/tmp.38WWwwIWYj.cue
_#fizzlebit: {a: string, ...} | {b: string, ...}
abc: _#fizzlebit & {
        a: "abcde"
}
% go run ./cmd/cue vet -c /tmp/tmp.38WWwwIWYj.cue
abc: incomplete value {a:"abcde"} | {a:"abcde",b:string}
exit status 1
```

(this isn't a new bug, either, I checked tags back to `v0.2.0` -- `v0.1.0` complains about he syntax)


side-note: I ran into this because `cue import` generates a constraint like this for the current version of the github actions jsonschema on[ the `steps`  field](https://github.com/SchemaStore/schemastore/blob/342b962b23f110476c7da2961ea35700e91d518d/src/schemas/json/github-workflow.json#L664-L684). In particular, the `oneof` requiring either a `run` field xor a `uses` field. (I ended up deleting the disjunction to enforce this as a workaround for this bug.

**Comment by mvdan** [comment]
The original example appears to export to YAML correctly without issue: https://cuelang.org/play/?id=QqfAXey5iwc#w=function&i=cue&f=export&o=yaml

I can't really say why it was broken before. The testscript below, which mimics what the playground does with `cue export`, passes now as it did back in CUE v0.7.1:

```
exec cue export --out yaml in.cue
cmp stdout stdout.yaml

-- stdout.yaml --
config:
  cue:
    resource:
      uri: https://cuelang.org
-- in.cue --
#uriSchema: {
    uri: string
}

#ipSchema: {
    ip: string
}

#resource: #uriSchema | #ipSchema


config: [string]: {
    resource: #resource
}

config: cue: {
    resource: {
        uri: "https://cuelang.org"
    }
}
```

And like @myitcv says, we improved the playground to mimic cmd/cue's behavior in https://github.com/cue-lang/cue/issues/2417, so it should be consistent - and it appears to be consistent today.

@dfinkel your issue appears to be unrelated. In the example below:

```
_#fizzlebit: {a: string, ...} | {b: string, ...}
abc: _#fizzlebit & {
        a: "abcde"
}
```

`abc` is indeed incomplete. `{a: "abcde"}` unifies correctly with both `{a: string, ...}` and `{b: string, ...}`, because both are open structs which allow declaring the field `a`.

> side-note: I ran into this because `cue import` generates a constraint like this for the current version of the github actions jsonschema on[ the `steps` field](https://github.com/SchemaStore/schemastore/blob/342b962b23f110476c7da2961ea35700e91d518d/src/schemas/json/github-workflow.json#L664-L684). In particular, the `oneof` requiring either a `run` field xor a `uses` field. (I ended up deleting the disjunction to enforce this as a workaround for this bug.

I believe you want to follow https://github.com/cue-lang/cue/issues/3165; supporting oneofs requires a new builtin in CUE, which is landing soon.
