### ISSUE TITLE
cuelang.org: frontend: playground should have a "cue fmt" button

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#2996]
### What page were you looking at?

https://cuelang.org/play/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/3953c5f0db191ef4bde57d5851d3ce67ac7ef45f

### What did you do?

I typed some messy CUE, and then had to manually format it.

### What did you expect?

I expected there to be a "cue fmt" button somewhere in the interface, which would format my CUE idiomatically for me.

### What did you see instead?

No "cue fmt" button.

**Comment by JorindeUsMedia** [comment]
We thought we had to do something with the codemirror editor but this is not the case. 
What we should do:

1. Add format button to input tabs: find a place in the ui to do this this.  Question: Should this button only be added when language is CUE @jpluscplusm @myitcv ?
2.  Add a function format(language) {}  and trigger when button is clicked. This functoin will do a call to a, (to be determined) endpoint/function on the webassembly part.
3. If wasm call is succesfull fill the input field where the format was called on with the input returned by wasm. If unsuccessufl leave input as it is but show a message somewhere (console?)

estimate: 1-2 hours

**Comment by JorindeUsMedia** [comment]
As discussed with Jonathan: the tabs themselves are already clickable for the language selection. For the function workspace this is not the case but for the other workspaces it is: 

![Image](https://github.com/user-attachments/assets/89869016-d4b5-4738-93b4-d11201bec3af)

I would not recommend adding the Copy filename & Format input to this same dropdown. I think it would be confusing from a usability perspective and it also would mean rewriting the code for the dropdowns because right now they are selecting a value from the list and don't have the option to have multiple actions attached to their values. I quickly put together something in the browser but to me this is really confusing: 

![Image](https://github.com/user-attachments/assets/a646eecd-680f-4a71-988b-837014478711)

So we have to think of a way where we can put the format button. Maybe not put in the tab? (note: could have a problem when we have multiple tabs) 
Quick sketches:

![Image](https://github.com/user-attachments/assets/4ef8e6e7-f4d6-47f9-8b65-33981553f624)
![Image](https://github.com/user-attachments/assets/d761a8dc-e9fb-4f5e-bc6f-840c93e36767)

**Comment by JorindeUsMedia** [comment]
@jpluscplusm @myitcv  see comment above: do you have an idea what the best place is for this button?

**Comment by JorindeUsMedia** [comment]
Discussed with Jonathan: 
We're going for a slightly different version of: 
![Image](https://github.com/user-attachments/assets/a646eecd-680f-4a71-988b-837014478711)

Languages are going to be nested below a heading "Languages" . We talked about this being also a dropdown but a dropdown in a dropdown is not really recommended. We can of course always change it if we want:

![Image](https://github.com/user-attachments/assets/abc6db5f-b172-42db-969f-3601f07255f7)

We could also format JSON & Yaml using the Codemirror editor but we discussed want to use wasm to format all languages : so also json & yaml if possible (policy playground). We're not sure if the wasmapi already supports that. If's not doable we can either grey out the option or let it not do anything. 

Edit : don't know why github is blowing up my drawing image :sweat_smile:
