### ISSUE TITLE
`cue get go` renders time.Duration with incorrect type

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2999]
### What version of CUE are you using (`cue version`)?

commit 1b9b0799

### Does this issue reproduce with the latest stable release?

N/A

### What did you do?

```
exec cue get go --local ./...

# Check that the generated schema is actually compatible
# with the JSON that the Go generates for the duration type.
exec go run ./pkg2
cp stdout s.json
exec cue vet s.json schema.cue

-- schema.cue --
package schema

import "mod.test/pkg1"

pkg1.#S

-- go.mod --
module mod.test

go 1.21
-- cue.mod/module.cue --
module: "mod.test"
-- pkg1/file1.go --
package pkg1

import "time"

type S struct {
	D time.Duration
}

const Time1Second = time.Second

-- pkg2/main.go --
package main

import (
	"encoding/json"
	"fmt"
	"time"

	"mod.test/pkg1"
)

func main() {
	data, _ := json.Marshal(pkg1.S{time.Second})
	fmt.Printf("%s\n", data)
}
```

### What did you expect to see?

A passing test. The generated schema should be compatible with the marshaled
JSON output from the Go that was the source of the schema.

### What did you see instead?

```
# Check that the generated schema is actually compatible
# with the JSON that the Go generates for the duration type. (0.188s)
> exec go run ./pkg2
[stdout]
{"D":1000000000}
> cp stdout s.json
> exec cue vet s.json schema.cue
[stderr]
D: conflicting values 1000000000 and time.Duration() (mismatched types int and string):
    ./pkg1/file1_go_gen.cue:9:8
    ./s.json:1:6
    ./schema.cue:5:1
[exit status 1]
FAIL: /tmp/testscript3715745262/x.txtar/script.txtar:7: unexpected command failure
```

Before https://cuelang.org/cl/1189718 landed, this was the failure. This was issue #2969.

```
# Check that the generated schema is actually compatible
# with the JSON that the Go generates for the duration type. (0.145s)
> exec go run ./pkg2
[stdout]
{"D":1000000000}
> cp stdout s.json
> exec cue vet s.json schema.cue
[stderr]
D: undefined field: #Duration:
    ./pkg1/file1_go_gen.cue:9:13
[exit status 1]
FAIL: /tmp/testscript3325476289/x.txtar/script.txtar:7: unexpected command failure
```

**Comment by mvdan** [comment]
cc @gdvalle. I missed this detail when I considered the original issue and patch.

I think we should have an integration test like the one that Roger shows above, covering the various standard library types that we translate into our own standard library APIs, to ensure that they roundtrip via JSON. To be clear, such a test should cover two cases: first, encoding from CUE and decoding from Go, and second, encoding from Go and decoding from CUE (like Roger shows above).

As for the `cue get go` change for this bug, with the assumption that we can't change https://pkg.go.dev/cuelang.org/go/pkg/time#Duration to accept nanosecond integers as it would be a breaking change, the simplest fix would be to avoid using our `time.Duration` API for now, and representing Go durations in CUE as `int64` in nanoseconds. Not ideal for sure, but at least compatible.

The best of both worlds might be to generate something like `int64 | time.Duration`, meaning that the CUE type would support unifying with nanosecond integers as encoded by `encoding/json`, but it would also support the "proper" `time.Duration` if a user prefers nice strings over compatibility with `encoding/json`. Importing a value rather than a type, like the original `time.Duration(time.Second)`, would omit this disjunction and always use the integer form.

It's worth noting that Go as an ecosystem is moving towards encoding durations as strings. See, for example, https://github.com/go-json-experiment/json?tab=readme-ov-file#behavior-changes and https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/duration.go. Really, the only reason that `encoding/json` marshals durations as integers is a historical mistake, but one that cannot be fixed without breaking Go's compatibility guarantee, so it's here for good. We should support it, but I don't want us to discard support for duration strings forever either.

**Comment by mvdan** [comment]
I have merged the fix to use `int` instead of `time.Duration` - it's not perfect, and it's not compatible with CUE's own `time.Duration`, but at least it's compatible with Go, which is more important for the sake of CUE+Go integrations, which is the entire point of `cue get go`.

I have left a TODO about revisiting this, to either make the behavior configurable or to use something like `int | *time.Duration`.
