### ISSUE TITLE
docs: export with optional fields specified

### ISSUE THREAD

**Issue by lasse16** [cue-lang/cue#3010]
Hi, this is a fairly unique approach I take.

I am using a CUE file as a schema to validate a YAML config, but I am also using the same schema to generate a YAML file with the required fields already made concrete.

However, the values for the required fields are coming from other users and are specified via a GitHub Issue. They never see the schema.
So, upon exporting, I would also like the exported YAML to also have the optional fields, so that users can see possible options without opening the schema.

Example: 
```cue
//schema.cue
field1: string tag(field1)
optional_field?: string
```
`cue export schema.cue yaml -t field1=<input from github issue>`
```yaml
//current result
field1: <input from github issue>
```
```yaml
//wished for result
field1: <input from github issue>
optional_field: string
```

Is there a CLI flag? 
Do you think this is even a good idea or is there a workaround? 
The generated YAML is not going to be valid so you might not intend to even have this functionality.

Many  thanks!

**Comment by jpluscplusm** [comment]
I don't believe there's a way to achieve this with just your current inputs, and the `cue` command. I suspect it'd be possible through the Go API, but that's not my area of expertise!

You could achieve it by adding some (potentially conditionally-included) files, like this:

```
exec cue export --out yaml -t field1='some value' -t optional
cmp stdout golden.yaml
-- schema.cue --
package p

field1: string @tag(field1)
optional_field?: string

-- optionalFields.cue --
@if(optional)
package p

optional_field: "string"
-- golden.yaml --
field1: some value
optional_field: string
```

If your source CUE is simple enough, I could see it being possible to hackily create the conditional files with `sed`/etc, but that's of course sub-optimal. Alternatively, you could maintain the two files in parallel, depending on how complex your schema is.

It's perhaps worth noting that your final line:

> The generated YAML is not going to be valid so you might not intend to even have this functionality.

... isn't actually the case, because YAML doesn't require quotes around strings. In my example, `golden.yaml` *is* valid YAML -- or `cue` wouldn't have created it!

**Comment by lasse16** [comment]
Ok, many thanks anyway!

I will close this issue then
