### ISSUE TITLE
cuelang.org: remove mention of "experimental"

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#3135]
### What page were you looking at?

https://cuelang.org/docs/tutorial/publishing-modules-to-the-central-registry/

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/24ebac4d1f007c850390e550704b7e08eeceee8a

In anticipation of https://github.com/cue-lang/cue/issues/3127 happening, we need to ensure that we remove mentions of "experimental" on cuelang.org where appropriate. This issue captures that work.

**Comment by jpluscplusm** [comment]
The page mentioned in the initial comment is fixed in https://cuelang.org/cl/1194896 which came out of https://github.com/cue-lang/docs-and-content/issues/147.

@myitcv does this issue track updates to the help texts (i.e. as per https://github.com/cue-lang/cue/issues/3151), or can it be closed as a duplicate of https://github.com/cue-lang/docs-and-content/issues/147?

**Comment by myitcv** [comment]
> @myitcv does this issue track updates to the help texts (i.e. as per #3151), or can it be closed as a duplicate of [cue-lang/docs-and-content#147](https://github.com/cue-lang/docs-and-content/issues/147)?

The latter, thanks for catching the dupes.

**Comment by myitcv** [comment]
Per the above exchange, the remainder of work here is captured by https://github.com/cue-lang/docs-and-content/issues/147 so closing this issue as complete.
