### ISSUE TITLE
cue cmd step fails to evaluate in dependency order with step that uses `{$id: "print"}`

### ISSUE THREAD

**Issue by infogulch** [cue-lang/cue#3191]
According to the documentation in cli.cue, `"print"` is a valid $id for the print tool:

https://github.com/cue-lang/cue/blob/a3b1138766dcaaab5f40bb229c18fe9497b30d9c/pkg/tool/cli/cli.cue#L19

However in practice if a step uses `{$id: "print"}` then it behaves strangely. Here is a minimal reproduction of the bug with two cmds: `cue cmd works` works as expected and captures stdout from the run step and prints it out, but `cue cmd bug` fails with `command.bug.print1.text: invalid string argument: invalid interpolation: non-concrete value string (type string)`. IMO this implies that the evaluator does not wait for the run step to complete before attempting to evaluate the print1 step:

```cue
package cmdid

import (
	"tool/exec"
	"tool/cli"
)

command: bug: {
	run: exec.Run & {
		cmd:    "echo hello world"
		stdout: string
	}
	print1: {$id: "print", text: string} & {text: "output: \(run.stdout)"}
}

command: works: {
	run: exec.Run & {
		cmd:    "echo hello world"
		stdout: string
	}
	print1: cli.Print & {text: "output: \(run.stdout)"}
}
```

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.2

go version go1.22.2
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

**Comment by myitcv** [comment]
@infogulch thanks for the report. In future, please can you stick to the bug report template? Looking through lots of issues, the template structure makes it clear and easy to follow. Deviations from that are, by definition, harder to parse/follow/interpret. Thanks

My suggestion here would be to not hard code `$id: "print"`. Instead you can do something like the following to "alias" the command once.

```
exec cue cmd bug
cmp stdout stdout.golden

-- x_tool.cue --
package cmdid

import (
	"tool/exec"
	"strings"
)

command: bug: {
	run: exec.Run & {
		cmd:    "echo hello world"
		stdout: string
	}
	print1: print & {
		text: "output: \(strings.TrimSpace(run.stdout))"
	}
}

-- y_tool.cue --
package cmdid

import "tool/cli"

print: cli.Print

-- stdout.golden --
output: hello world
```

The reason is that `"print"` (or indeed `"tool/cli.Print"`) are in effect internal details.
