### ISSUE TITLE
cuelang.org: playground frequently gets stuck at "... loading WASM" 

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3271]
### What page were you looking at?

https://cuelang.org/play/?id=6sgdmi8vArV#w=function&i=cue&f=eval&o=cue

### What version of the site were you looking at?

https://github.com/cue-lang/cuelang.org/commit/c151815c80d0686e318a724870f5a6ab9b831678

### What did you do?

I opened a playground URL pointing to some saved CUE. 

### What did you expect?

The page to work.

### What did you see instead?

The page's RHS stuck at "loading WASM":

![image](https://github.com/cue-lang/cue/assets/224508/33b5ea4c-b602-465d-8ecf-e4d4900c20ab)

**Comment by jpluscplusm** [comment]
This appears unrelated to the specific saved CUE URL that's opened, but it does seem to strike more often when loading saved CUE rather than opening the playground's front page.

It's easiest to trigger when opening the page in a newly minted incognito/private/etc window.

A page refresh sometimes fixes it, but sometimes doesn't. I've experienced it being fixed after I clicked the browser's reload button twice (Chrome on ChromeOS). 30 seconds later, with a new incognito window, those same clicks didn't fix it after 6 reloads, but then a Ctrl-Shift-R ("hard"?) refresh worked the first time. Was that coincidence, or did the "hard" refresh actually do something different, cache-related? 

The headline "page is stuck" issue has been confirmed (by @myitcv) on a totally different network, machine, and OS.

**Comment by myitcv** [comment]
FWIW, I see it stuck on `loading WASM` ~100% of the time.

**Comment by myitcv** [comment]
Making on observation on how to "fix" such a page that is stuck, making a change in the LHS pane "fixes" the RHS side. This points to the initial editor state being bad: i.e. the WASM file has loaded _before_ the editor renders for the first time, but regardless the initial editor state is rendered as `loading WASM`. Because the file has already loaded, there is then no further state change that would trigger a re-render, unless (as explained) you trigger such a state change by adding a space (for example) to the LHS input
