### ISSUE TITLE
Unclear error messsages when tag is not provided in _tool.cue commands

### ISSUE THREAD

**Issue by Kryan90** [cue-lang/cue#3357]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
go version go1.22.5
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH arm64
            GOOS darwin
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?
1. Add a tag variable and don't provide a value when invoking
```cue
package scripts

import (
	"tool/cli"
)

#args: {
	myVar: string @tag(myVar)
}

command: print: {
	print: cli.Print & {
		text: #args.myVar
	}
}
```

```bash
❯ cue cmd print .
command.print.print.text: invalid string argument: non-concrete value string:
    ./test_tool.cue:12:2
    ./test_tool.cue:13:3
    tool/cli:4:3
    tool/cli:4:9

```

2. I also tried to mark the tagged variable as required, but this does not seem to be supported
```cue
#args: {
	myVar!: string @tag(myVar)
}
```

```bash
❯ cue cmd print .
@tag not allowed within field constraint:
    ./test_tool.cue:8:17
```

### What did you expect to see?
An error clearing stating what variable was not provided, ie.
```bash
command.print.print.text: invalid string argument: non-concrete value string: myVar is required:
...
```

### What did you see instead?
A less clear error message that is much more difficult for users of my tool to debug on their own without having to dig through the source files

**Comment by myitcv** [comment]
@Kryan90 thanks for raising this. It's very interesting that your intuition here is that `@tag` represents some sort of indicator for a required input. Whilst that is one way in which a value could provided, it's not the only way: a user could, in theory, include a value in another file (not that `cue cmd` supports that in an elegant way today). 

But I think your intuition is solid, especially because you declared the inputs under `#args` - it has the feel of needing/wanting to be explicit (and type-safe). 

That said, I think this discussion belongs as part of https://github.com/cue-lang/cue/issues/1325. I've updated the top-level description to capture your feedback. Please let me know if I haven't done it justice. 

On the basis we are unlikely to do more work on `cue cmd` as it stands today, and are instead going to focus efforts towards a v2 in https://github.com/cue-lang/cue/issues/1325, I will close this issue for now. 

Thanks again the feedback.
