### ISSUE TITLE
Unexpected disjunction behavior with default value

### ISSUE THREAD

**Issue by vofilin** [cue-lang/cue#3421]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.10.0

go version go1.23.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.10.0
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

<pre>
cue export configuration.cue

-- configuration.cue --
_#schemas: env: [string]: string

_#extStruct: this={
    env: _#schemas.env
    intStruct: {
        env: _#schemas.env | *this.env
    }
}

app: _#extStruct & {
    env: env1: "testenv1"
    intStruct: {
        env: env2: "testenv2"
    }
}
</pre>

### What did you expect to see?

<pre>
{
    "app": {
        "env": {
            "env1": "testenv1"
        },
        "intStruct": {
            "env": {
                "env2": "testenv2",
            }
        }
    }
}
</pre>

### What did you see instead?

<pre>
{
    "app": {
        "env": {
            "env1": "testenv1"
        },
        "intStruct": {
            "env": {
                "env2": "testenv2",
                "env1": "testenv1"
            }
        }
    }
}
</pre>

**Comment by mvdan** [comment]
This is working as intended, as far as I can tell.

`app.env` unifies `{[string]: string}` with `{env1: "testenv1"}`, so it remains an open struct as follows:

```
app: env: {
    env1: "testenv1"
    [string]: string
}
```

`app.intStruct.env` unifies `{[string]: string} | *this.env` with `{env2: "testenv2"}`. Since both sides of the disjunction on the left side unify with the right side (because they are both open structs with `[string]: string`), the default is picked, so you end up with both fields:

```
app: intStruct: env: {
    env1: "testenv1"
    env2: "testenv2"
    [string]: string
}
```

It's hard to understand what you're trying to do, but this is working as intended following the spec. I would suggest starting a discussion on GitHub or starting a thread on Slack or Discord if you would like some help.
