### ISSUE TITLE
OOM crash when using cuecontext.CompileString

### ISSUE THREAD

**Issue by bobcallaway** [cue-lang/cue#3574]
### What version of CUE are you using (`cue version`)?

<pre>
reproduces on v0.10.1 and v0.9.2 of cuelang.org/go
</pre>

### Does this issue reproduce with the latest stable release?

yes

### What did you do?

This was found via oss-fuzz, and can be locally reproduced with the following go code:

```go
package main

import (
	"fmt"

	"cuelang.org/go/cue/cuecontext"
)

const (
	evalStr = "12e82-1/222+221000280*[5e5]/2222/22222/22222220*0*642"
)

func main() {
	cueCtx := cuecontext.New()
	cueEvaluator := cueCtx.CompileString(evalStr) // killed with OOM signal
	if cueEvaluator.Err() != nil {
		fmt.Printf("failed to compile the cue policy with error: %w", cueEvaluator.Err())
		return
	}
}
```

when running this, the program is killed by the kernel due to OOM:

```sh
$ go version
go version go1.23.2 darwin/arm64
$ cat go.mod|grep cue
	cuelang.org/go v0.10.1
	cuelabs.dev/go/oci/ociregistry v0.0.0-20240807094312-a32ad29eed79 // indirect
$ go run repro3.go 
signal: killed
```

### What did you expect to see?

any return from `cueCtx.CompileString()` call instead of OOM kill

### What did you see instead?

killed by kernel due to OOM

**Comment by rogpeppe** [comment]
The problem here is that currently the CUE evaluator supports a deprecated syntax for multiplying a slice by a number.
For example `[1] * 5` results in `[1,1,1,1,1]`.

So the example above contains `221000280*[5e5]` which will create a slice of 200 million floats, which given CUE's not-very-efficient storage of scalars, is almost certainly what's using all your memory.

If we change the large number to a smaller one, the expression returns an error immediately:

```
invalid operands [{x},{x},{x},{x}] and 2222 to '/' (type list and int):
    -:1:13
    -:1:21
```

So this is functioning as designed. However, it could be argued that an earlier phase of type checking
could ensure that the expensive operations aren't executed because we can tell there's a type error
even without running them. That would be a significant feature enhancement though, so I think
this issue can be closed as is.
