### ISSUE TITLE
evalv3: disjunct of definitions that each reference an identical optional field results in incomplete evaluation

### ISSUE THREAD

**Issue by marxarelli** [cue-lang/cue#3576]
I am trying out the v3 evaluator with an existing project and ran into some strange behavior with regards to incomplete (or unsimplified?) evaluation. After completely paring down my schema, I was able to repro the issue with the minimal configuration below.

Note that the golden examples below are from the v2 evaluator.

<pre>
exec cue version
env CUE_EXPERIMENT=evalv3
exec cue eval -e foo foo.cue
cmp stdout stdout.golden

-- foo.cue --
#Run: {
	run!: string
	options?: #Option | [#Option, ...]
	if options != _|_ {
		optionsValue: options
	}
}

#Copy: {
	copy!: string
	options?: #Option | [#Option, ...]
	if options != _|_ {
		optionsValue: options
	}
}

#Option: {}

foo: #Run | #Copy
foo: run: "make"

-- stdout.golden --
run: "make"
</pre>

If I remove the conditional, the entire evaluation result is empty.

<pre>
env CUE_EXPERIMENT=evalv3
exec cue eval -e foo foo.cue
cmp stdout stdout.golden

-- foo.cue --
#Run: {
	run!: string
	options?: #Option | [#Option, ...]
	optionsValue: options
}

#Copy: {
	copy!: string
	options?: #Option | [#Option, ...]
	optionsValue: options
}

#Option: {}

foo: #Run | #Copy
foo: run: "make"

-- stdout.golden --
run: "make"
</pre>

(BTW, thanks for all the hard work on the new evaluator. I'm very much looking forward to it when it's ready.)

**Comment by myitcv** [comment]
@marxarelli thanks for the repro. 

(For future bug reports, please use the "Bug report" issue so that we can capture details about version, expectations etc in a standard form: https://github.com/cue-lang/cue/issues/new/choose. It makes human parsing of such issues much easier!)

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20241208202749-5149ebdd9829

go version go1.23.2
      -buildmode exe
       -compiler gc
  DefaultGODEBUG asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
         GOARM64 v8.0
             vcs git
    vcs.revision 5149ebdd9829d23e29a676c87f89d2851f1c3134
        vcs.time 2024-12-08T20:27:49Z
    vcs.modified false
cue.lang.version v0.12.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes with v0.11.0

### What did you do?

```
# evalv2
env CUE_EXPERIMENT=evalv3=0
exec cue eval -e foo foo.cue
cmp stdout stdout.golden

# evalv3
env CUE_EXPERIMENT=evalv3=1
exec cue eval -e foo foo.cue
cmp stdout stdout.golden

-- foo.cue --
#Run: {
	run!: string
	options?: #Option | [#Option, ...]
	if options != _|_ {
		optionsValue: options
	}
}

#Copy: {
	copy!: string
	options?: #Option | [#Option, ...]
	if options != _|_ {
		optionsValue: options
	}
}

#Option: {}

foo: #Run | #Copy
foo: run: "make"

-- stdout.golden --
run: "make"
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
# evalv2 (0.021s)
# evalv3 (0.028s)
> env CUE_EXPERIMENT=evalv3=1
> exec cue eval -e foo foo.cue
[stdout]
{
    run: "make"
} | {
    run:   _|_ // foo.run: field not allowed
    copy!: string
}
> cmp stdout stdout.golden
diff stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -1,6 +1,1 @@
-{
-    run: "make"
-} | {
-    run:   _|_ // foo.run: field not allowed
-    copy!: string
-}
+run: "make"

FAIL: /tmp/testscript327642522/repro.txtar/script.txtar:9: stdout and stdout.golden differ
```

i.e. evalv3 is broken compared to evalv2.

**Comment by mpvl** [comment]
Analysis: the issue is that although V3 correctly identifies the faulty disjunct it does not end up eliminating it.

Apparently, using `-e` on incomplete values than causes to drop it, which is a separate bug that may even exist in V2 as well.

**Comment by mpvl** [comment]
In fact, the error is just not propagated up.

Here is a smaller reproducer:
```
#Run: run!: string
#Copy: {
	copy!: string
	if false {
		dummy: {}
	}
}

foo: #Run | #Copy
foo: run: "make"
```
