### ISSUE TITLE
cmd/cue: structural cycle reported where there doesn't appear to be one

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#754]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/754_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +760aa115 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval

-- x.cue --
package main

Template: {
	from: _

	task: from
}

C: Template & {
	from: Template & {
		from: Template & {}
	}
}
```

### What did you expect to see?

Passing test with output:

```
C: {
    from: {
        from: {}
    }
}
```

### What did you see instead?

```
> exec cue eval
[stderr]
C.task.task: structural cycle
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/754#issuecomment-792548580_

Analysis: this is indeed not a structural cycle. This very specific pattern simulates Template referencing itself, which is what cycle detection picks up (note that the cycle is in `C.task.task`, not `C.from.from`).

This is best addressed moving to structure sharing. A side-benefit of structure sharing is making it considerably easier to do cycle detection (as well as implementing concurrency, see graph-unification papers from Tomabechi and Van Lohuizen).

**Comment by myitcv** [comment]
Paging @mpvl to confirm whether this is fixed in the upcoming cycle changes or not.

**Comment by jlongtine** [comment]
@myitcv @mpvl I just attempted this with 537831: internal/core/adt: reimplementation of cycle algorithm | https://review.gerrithub.io/c/cue-lang/cue/+/537831, and the issue remains. 

```
> exec cue eval
[stderr]
C.task.task: structural cycle
[exit status 1]
FAIL: /var/folders/bc/sp1mwn2d4r5859bw3k2dz4bc0000gn/T/testscript290649163/testscript3.txt/script.txt:1: unexpected command failure
error running testscript3.txt in /var/folders/bc/sp1mwn2d4r5859bw3k2dz4bc0000gn/T/testscript290649163/testscript3.txt
```

**Comment by mpvl** [comment]
Hmmm, this is indeed still a cycle in the new implementation. Luckily the new algorithm is a lot easier to comprehend, so I can see why it is doing this.

Analysis:

Note that this case is very similar to the example in "The Logic of Type Feature Structures" (Bob Carpenter), which explains how the unification of two non-cyclic structures can result in a cyclic one. In CUE terms:
```
y: {
	f: h: g
	g: _
}
x: {
	f: _
	g: f
}
z: x & y
```

Except that in this case it actually isn't a cycle. A subtle but important difference. Here is a simpler reproducer:
```
Template: {
	from: _
	task: from
}

C: Template & {
	from: Template
}
```
This only fails in the new implementation, actually. But that is only because the new one is a bit "tighter", the mechanism by which it fails is more or less the same: it detects a reoccurring reference as a cycle, even though it is paired with new structure.

The solution is to erase reference tracking for conjuncts that are unified with a "new" conjunct. This makes it harder to prove that evaluation will always terminate, but of course that is still desirable over an incorrect algorithm. :)
